import streamlit as st
from PIL import Image
import traceback
import re
from pathlib import Path
import sys
from healthcare_rag_llm.filters.load_metadata import build_filter_extractor
import html
from datetime import date, datetime

# ============================================================
# ========== PATH SETUP ======================================
# ============================================================
st.set_page_config(page_title="NYS Policies Assistant", layout="wide")

ROOT = Path(__file__).resolve().parents[1]  # project root
SRC_DIR = ROOT / "src"
sys.path.append(str(SRC_DIR))  # allow import from src/

# ============================================================
# ========== IMPORT PIPELINE MODULES =========================
# ============================================================
try:
    from healthcare_rag_llm.llm.llm_client import LLMClient
    from healthcare_rag_llm.llm.response_generator import ResponseGenerator
    #from healthcare_rag_llm.llm.guardrail_response_wrapper import ResponseGenerator
    HAS_BACKEND = True
except Exception as e:
    
    HAS_BACKEND = False
    st.exception(e)
    st.code(traceback.format_exc())
    st.warning(f"⚠️ Backend import failed: {e}. Mock mode enabled.")

# ============================================================
# ========== STREAMLIT PAGE CONFIG ===========================
# ============================================================
# Paths
ROOT_DIR = Path(__file__).parent
ASSETS_DIR = ROOT_DIR / "assets"
nys_logo_path = ASSETS_DIR / "nys_logo.png"

# ============================================================
# ========== HEADER ==========================================
# ============================================================
col1, col2 = st.columns([5, 1])
with col1:
    st.title("NYS Healthcare Policies Assistant")
    st.caption("An AI-powered assistant for navigating New York State medical care policies.")
with col2:
    if nys_logo_path.exists():
        nys_logo = Image.open(nys_logo_path)
        st.image(nys_logo, width=200)
    else:
        st.text("NYS Logo Missing")

# ============================================================
# ============================================================
# ========== DISCLAIMER ======================================
# ============================================================
with st.expander("📜 Disclaimer", expanded=True):
    st.markdown("""
This assistant is part of the **Columbia University x KPMG Capstone Project**:
*Intelligent Document Analysis for Healthcare Programs Using LLMs and RAG.*

The responses are generated by an AI model referencing official
New York State Medicaid documents and related authorities.
They do not constitute legal advice.
""")

with st.expander("ℹ️ About and How It Works", expanded=True):
    st.markdown("""
**Purpose (Q&A)**  
Ask one policy question and get a grounded, cited answer.

**How it works**  
We retrieve relevant NYS Medicaid sources and generate a response with citations.

**Tips**  
Use specific terms (program, topic, date range) and verify against citations.
""")

# ========== INITIALIZE RAG PIPELINE =========================
# ============================================================
@st.cache_resource
def load_rag_pipeline():
    if not HAS_BACKEND:
        return None
    from healthcare_rag_llm.utils.api_config import APIConfigManager
    api_config_manager = APIConfigManager()
    api_config_default = api_config_manager.get_default_config()
    provider = (api_config_default.provider or "").lower()
    provider_to_model = {
        "deepseek": "deepseek-chat",
        "gemini": "gemini-2.5-flash",
        # Use a widely available OpenAI-compatible fallback.
        "openai": "gpt-4o-mini",
    }
    model = provider_to_model.get(provider, "deepseek-chat")
    llm_client = LLMClient(
        api_key=api_config_default.api_key,
        model=model,
        provider=api_config_default.provider,
        base_url=api_config_default.base_url
    )
    filter_extractor = build_filter_extractor()
    return ResponseGenerator(llm_client,filter_extractor=filter_extractor)

def get_rag_pipeline_lazy():
    """Create the RAG pipeline only when user submits a query."""
    if "rag_pipeline" not in st.session_state:
        st.session_state["rag_pipeline"] = load_rag_pipeline()
    return st.session_state["rag_pipeline"]


def _remove_none_caveats(text: str) -> str:
    """
    Remove the Caveats section only when model explicitly returns None.
    This follows prompt contract and avoids semantic guessing.
    """
    # Remove one-line forms like "Caveats: None" (case-insensitive, optional markdown)
    single_line_pattern = re.compile(
        r"(?im)^\s*\*{0,2}caveats\*{0,2}\s*:\s*(?:\*{0,2}_?`?none`?_?\*{0,2})\s*$"
    )
    text = re.sub(single_line_pattern, "", text)

    # Remove section forms like:
    # Caveats:
    # None
    pattern = re.compile(
        r"(?ims)^\s*\*{0,2}caveats\*{0,2}\s*:?\s*\n(?P<body>.*?)(?=^\s*\*{0,2}(answer|evidence(?:\s*\([^)]*\))?|retrieved sources?)\*{0,2}\s*:?\s*$|\Z)"
    )
    m = pattern.search(text)
    if not m:
        return text

    body = m.group("body").strip()
    normalized = re.sub(r"^[\s\-*•]+", "", body).strip().lower()
    if normalized in {"none", "**none**", "_none_", "`none`"}:
        return (text[:m.start()] + text[m.end():]).strip()
    return text


def _extract_answer_only(text: str) -> str:
    """
    Keep only the answer portion of the model output so UI-controlled Evidence
    and recency blocks can be rendered in a stable order.
    """
    if not text:
        return ""

    cleaned = text.strip()
    cleaned = re.sub(r'^answer\s*:?\s*', '', cleaned, count=1, flags=re.IGNORECASE).strip()
    cleaned = _remove_none_caveats(cleaned)

    evidence_match = re.search(r'(?im)^\s*\*{0,2}evidence(?:\s*\([^)]*\))?\*{0,2}\s*:?\s*$', cleaned)
    if evidence_match:
        cleaned = cleaned[:evidence_match.start()].rstrip()

    return cleaned


def format_evidence_dict(evidence_dict):
    """format evidence_dict as HTML list"""
    if not evidence_dict:
        return "No evidence returned."

    html_lines = []
    for i, (key, ev) in enumerate(evidence_dict.items(), 1):
        doc_info = html.escape(str(ev.get("doc_info", "Unknown")))
        quote = html.escape(str(ev.get("quote", ""))).replace("\n", "<br>")
        publish_date = html.escape(str(ev.get("publish_date", "N/A")))
        url = html.escape(str(ev.get("url", "N/A")))

        html_lines.append(
            "<li>"
            f"<strong>{doc_info}</strong>, Published on {publish_date}: "
            f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\">{url}</a>"
            f"<div style=\"margin-top:0.35rem; padding-left:0.75rem; border-left:3px solid #E0E0E0; color:#333;\">{quote}</div>"
            "</li>"
        )

    return "\n".join(html_lines)


def format_retrieved_docs(retrieved_docs):
    """format retrieved_docs as markdown list"""
    if not retrieved_docs:
        return ""

    html_lines = []
    for doc in retrieved_docs:
        title = html.escape(str(doc.get("title", "")))
        doc_id = html.escape(str(doc.get("doc_id", "Unknown")))
        display_name = title if title else doc_id
        url = html.escape(str(doc.get("url", "N/A")))
        effective_date = html.escape(str(doc.get("effective_date", "N/A")))

        pages = html.escape(str(doc.get("pages", "N/A")))
        snippet = html.escape(str(doc.get("text", ""))[:300]).replace("\n", " ")

        html_lines.append(
            "<li>"
            f"<strong>{display_name}</strong> (pages {pages})<br>"
            f"<span style=\"color:#666; font-size:0.9em;\">Effective date: {effective_date}</span><br>"
            f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\">{url}</a><br>"
            f"<span style=\"color:#666; font-size:0.9em;\">{snippet}...</span>"
            "</li>"
        )

    return "\n".join(html_lines)


def _parse_effective_date(value):
    """Best-effort parse for effective dates used in Q&A recency display."""
    if not value:
        return None
    if isinstance(value, date) and not isinstance(value, datetime):
        return value
    if isinstance(value, datetime):
        return value.date()
    raw = str(value).strip()
    if not raw or raw.upper() == "N/A":
        return None
    for parser in (
        lambda s: datetime.fromisoformat(s).date(),
        lambda s: datetime.strptime(s, "%Y-%m-%d").date(),
        lambda s: datetime.strptime(s, "%B %Y").date(),
        lambda s: datetime.strptime(s, "%b %Y").date(),
        lambda s: datetime.strptime(s, "%B %d, %Y").date(),
        lambda s: datetime.strptime(s, "%b %d, %Y").date(),
    ):
        try:
            return parser(raw)
        except ValueError:
            continue
    return None


def format_recency_summary(retrieved_docs):
    """Create a visible recency summary from retrieved Q&A sources."""
    if not retrieved_docs:
        return ""

    dated_docs = []
    for doc in retrieved_docs:
        parsed = _parse_effective_date(doc.get("effective_date"))
        if parsed is not None:
            dated_docs.append((parsed, doc))

    if not dated_docs:
        summary = (
            "Most up-to-date source signal: recency could not be determined from the "
            "retrieved sources because no usable effective dates were available."
        )
    else:
        dated_docs.sort(key=lambda item: item[0], reverse=True)
        newest_doc = dated_docs[0][1]
        newest_title = html.escape(str(newest_doc.get("title") or newest_doc.get("doc_id") or "Unknown Document"))
        newest_date = html.escape(str(newest_doc.get("effective_date") or "N/A"))
        summary = (
            "Most up-to-date source signal: "
            f"the newest retrieved source is <strong>{newest_title}</strong> "
            f"(effective date: {newest_date})."
        )

    return (
        "<div style='margin:0.4rem 0 0.8rem 0; padding:10px 12px; background:#EEF6FF; "
        "color:#333; border:1px solid #CFE3FF; border-radius:8px;'>"
        f"{summary}</div>"
    )


# ============================================================
# ========== CHAT MODE (Multiple Q&A) ========================
# ============================================================
# Initialize history
if "history" not in st.session_state:
    st.session_state["history"] = []  # [{"role": "user"/"assistant", "content": "..."}]

# Container: display history (natural order)
chat_container = st.container()

# ============================================================
# ========== DISPLAY CHAT HISTORY (layout) ===================
# ============================================================
st.markdown(
    """
    <style>
    /* container */
    .chat-container { display: flex; flex-direction: column; gap: 1rem; margin-bottom: 1rem; font-size: 15px; }

    /* chat row */
    .chat-row { display: flex; align-items: flex-start; }
    .chat-row.user { justify-content: flex-end; }

    /* chat bubble */
    .chat-bubble {
        max-width: 90%;
        padding: 0.7rem 1rem;
        border-radius: 1rem;
        line-height: 1.6;
        word-wrap: break-word;
        box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }
    .chat-bubble.assistant {
        background-color: #F4F4F4;
        border: 1px solid #E0E0E0;
        color: #000 !important;
        border-top-left-radius: 0.3rem;
    }
    .chat-bubble.assistant * {
        color: #000 !important;
    }
    .chat-bubble.assistant a {
        color: #1a6dd4 !important;
    }
    .chat-bubble.user {
        background-color: #DCF2FF;
        border: 1px solid #CDE9FF;
        color: #000 !important;
        border-top-right-radius: 0.3rem;
    }
    .chat-bubble.user * {
        color: #000 !important;
    }

    /* avatar */
    .avatar {
        width: 36px; height: 36px;
        border-radius: 50%;
        display: flex; align-items: center; justify-content: center;
        font-size: 18px; font-weight: bold;
        background-color: #E5E7EB;
        margin: 0 0.5rem;
    }
    .avatar.user { background-color: #CDE9FF; }

    /* font */
    input, button, label, div[data-testid="stMarkdownContainer"] {
        font-size: 15px !important;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Load history
st.markdown('<div class="chat-container">', unsafe_allow_html=True)
for msg in st.session_state["history"]:
    role = msg["role"]
    text = msg["content"]

    if role == "assistant":
        evidence_dict = msg.get("evidence_dict", {})
        formatted_evidence = format_evidence_dict(evidence_dict)
        retrieved_docs = msg.get("retrieved_docs", [])
        formatted_sources = format_retrieved_docs(retrieved_docs) if retrieved_docs else ""
        recency_summary_html = format_recency_summary(retrieved_docs) if retrieved_docs else ""

        display_text = _extract_answer_only(text)
        display_html = html.escape(display_text).replace("\n", "<br>")

        answer_parts = []
        answer_parts.append("<b>Answer:</b><br>")
        if recency_summary_html:
            answer_parts.append(recency_summary_html)
        answer_parts.append(f"<p>{display_html}</p>")
        if evidence_dict:
            answer_parts.append(
                "<b>Evidence:</b><br>"
                "<em>Direct quotes from official documents that support the answer above.</em>"
                f"<ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_evidence}</ul>"
            )
        if retrieved_docs:
            answer_parts.append(
                "<b>Retrieved Sources:</b><br>"
                "<em>Document snippets that were retrieved and analyzed to answer your question.</em>"
                f"<ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_sources}</ul>"
            )

        full_html = (
            '<div class="chat-row assistant">'
            '<div class="avatar assistant">&#x1F914;</div>'
            '<div class="chat-bubble assistant">'
            + "".join(answer_parts)
            + "</div></div>"
        )
        st.markdown(full_html, unsafe_allow_html=True)
    else:
        safe_text = html.escape(text)
        st.markdown(
            f"""<div class="chat-row user">
                <div class="chat-bubble user">{safe_text}</div>
                <div class="avatar user">&#x1F464;</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
st.markdown('</div>', unsafe_allow_html=True)

# ============================================================
# ========== FOLLOW-UP QUESTION BUTTONS ======================
# ============================================================
is_generating_answer = "pending_query" in st.session_state

followup_area = st.empty()
if (not is_generating_answer) and st.session_state["history"]:
    last_msg = st.session_state["history"][-1]
    if last_msg.get("role") == "assistant":
        has_suggestions = bool(last_msg.get("followup_questions"))
        if has_suggestions:
            with followup_area.container():
                st.markdown("**Suggested follow-up questions:**")
                cols = st.columns(len(last_msg["followup_questions"]))
                for i, (col, q) in enumerate(zip(cols, last_msg["followup_questions"])):
                    with col:
                        if st.button(q, key=f"followup_{i}"):
                            st.session_state["history"].append({"role": "user", "content": q})
                            st.session_state["pending_query"] = q
                            st.session_state["pending_compare"] = False
                            st.session_state["pending_is_followup"] = True
                            st.rerun()

# ============================================================
# ========== INPUT AREA (two-line layout) ====================
# ============================================================
input_area = st.empty()
submitted = False
followup_submitted = False
cleared = False

if not is_generating_answer:
    with input_area.container():
        st.markdown('<div class="input-box">', unsafe_allow_html=True)

        with st.form("chat_form", clear_on_submit=True):
            user_query = st.text_input(
                "💬 **Ask a Question:**",
                placeholder="e.g. When did redetermination begin for the COVID-19 Public Health Emergency unwind in New York State?",
            )

            has_assistant_response = any(
                msg.get("role") == "assistant" for msg in st.session_state["history"]
            )

            if has_assistant_response:
                col1, col2 = st.columns([1, 1])
                with col1:
                    followup_submitted = st.form_submit_button("↪️ Ask Follow-Up", use_container_width=True)
                with col2:
                    cleared = st.form_submit_button("🧹 Clear Chat", use_container_width=True)
            else:
                submitted = st.form_submit_button("📤 Submit", use_container_width=True)

        st.markdown('</div>', unsafe_allow_html=True)

# Clear logic
if cleared:
    st.session_state["history"] = []
    rag_pipeline = st.session_state.get("rag_pipeline")
    if rag_pipeline:
        try:
            rag_pipeline.chat_history.clear()
        except Exception as e:
            st.error(f"Error clearing chat history: {e}")
    st.rerun()

# Submit logic ? phase 1: save query and rerun so the user message renders first
if submitted:
    if not user_query.strip():
        st.warning("Please enter a question before submitting.")
    else:
        # New question from input box ? clear previous context
        st.session_state["history"] = [{"role": "user", "content": user_query}]
        rag_pipeline = st.session_state.get("rag_pipeline")
        if rag_pipeline:
            try:
                rag_pipeline.chat_history.clear()
            except Exception:
                pass
        st.session_state["pending_query"] = user_query
        st.session_state["pending_is_followup"] = False
        st.rerun()

if followup_submitted:
    if not user_query.strip():
        st.warning("Please enter a follow-up question before submitting.")
    else:
        st.session_state["history"].append({"role": "user", "content": user_query})
        st.session_state["pending_query"] = user_query
        st.session_state["pending_is_followup"] = True
        st.rerun()

# Submit logic ? phase 2: generate answer (runs on the rerun, user message already visible)
if "pending_query" in st.session_state:
    pending_query = st.session_state.pop("pending_query")
    pending_is_followup = st.session_state.pop("pending_is_followup", False)
    with st.spinner("Retrieving information..."):
        try:
            rag_pipeline = get_rag_pipeline_lazy()
            if rag_pipeline:
                # --- Real backend ---
                history_for_llm = st.session_state["history"] if pending_is_followup else []
                result = rag_pipeline.answer_question(pending_query, history=history_for_llm)
                answer = result.get("answer", "No answer returned.")
                evidence_dict = result.get("evidence_dict", {})
                retrieved_docs = result.get("retrieved_docs", [])
                followup_questions = result.get("followup_questions", [])
            else:
                # --- Mock mode ---
                answer = (
                    "Mock mode: Backend not connected.\n"
                    "No grounded answer can be generated. "
                    "Please connect the backend (RAG pipeline) to enable cited answers."
                )
                evidence_dict = {}
                retrieved_docs = []
                followup_questions = []
            st.session_state["history"].append({
                "role": "assistant",
                "content": answer,
                "evidence_dict": evidence_dict,
                "retrieved_docs": retrieved_docs,
                "followup_questions": followup_questions,
            })
            st.rerun()
        except Exception as e:
            st.session_state["history"].pop()  # remove orphaned user message
            st.error(f"Error: {e}")


# ============================================================
# ========== BACKEND MEMORY VIEWER (for debugging) ===========
# ============================================================

# if rag_pipeline and hasattr(rag_pipeline, "chat_history"):
#     with st.expander("🧠 Backend Memory Viewer", expanded=False):
#         if hasattr(rag_pipeline.chat_history, "messages"):
#             messages = rag_pipeline.chat_history.get_messages()
#             if not messages:
#                 st.caption("*(Empty – no conversation stored in backend memory)*")
#             else:
#                 for i, msg in enumerate(messages, 1):
#                     role = msg["role"].capitalize()
#                     content = msg["content"][:1000]  # 截断长文本防止爆页面
#                     st.markdown(f"**{i}. {role}:** {content}")
#         else:
#             st.caption("ChatHistory not initialized or has no messages attribute.")

# # ============================================================
# # ========== FOOTER ==========================================
# # ============================================================
# st.divider()
# st.markdown(
#     "<p style='font-size: small; color: gray;'>© 2025 Columbia DSI x KPMG | For educational use only.</p>",
#     unsafe_allow_html=True
# )
