import streamlit as st
from PIL import Image
import traceback
from pathlib import Path
import sys
from healthcare_rag_llm.filters.load_metadata import build_filter_extractor
import html
from textwrap import dedent

# ============================================================
# ========== PATH SETUP ======================================
# ============================================================
st.set_page_config(page_title="NYS Policies Assistant", layout="wide")

ROOT = Path(__file__).resolve().parents[1]  # project root
SRC_DIR = ROOT / "src"
sys.path.append(str(SRC_DIR))  # allow import from src/

# ============================================================
# ========== IMPORT PIPELINE MODULES =========================
# ============================================================
try:
    from healthcare_rag_llm.llm.llm_client import LLMClient
    from healthcare_rag_llm.llm.response_generator import ResponseGenerator
    #from healthcare_rag_llm.llm.guardrail_response_wrapper import ResponseGenerator
    HAS_BACKEND = True
except Exception as e:
    
    HAS_BACKEND = False
    st.exception(e)
    st.code(traceback.format_exc())
    st.warning(f"⚠️ Backend import failed: {e}. Mock mode enabled.")

# ============================================================
# ========== STREAMLIT PAGE CONFIG ===========================
# ============================================================
# Paths
ROOT_DIR = Path(__file__).parent
ASSETS_DIR = ROOT_DIR / "assets"
nys_logo_path = ASSETS_DIR / "nys_logo.png"

# ============================================================
# ========== HEADER ==========================================
# ============================================================
col1, col2 = st.columns([5, 1])
with col1:
    st.title("NYS Healthcare Policies Assistant")
    st.caption("An AI-powered assistant for navigating New York State medical care policies.")
with col2:
    if nys_logo_path.exists():
        nys_logo = Image.open(nys_logo_path)
        st.image(nys_logo, width=200)
    else:
        st.text("NYS Logo Missing")

# ============================================================
# ========== DISCLAIMER ======================================
# ============================================================
with st.expander("📜 Disclaimer & About", expanded=True):
    st.markdown("""
    This assistant is part of the **Columbia University x KPMG Capstone Project**:
    *Intelligent Document Analysis for Healthcare Programs Using LLMs and RAG.*

    The responses are generated by an AI model referencing official
    New York State Medicaid documents and related authorities.
    They do not constitute legal advice.
    """)

# ============================================================
# ========== INITIALIZE RAG PIPELINE =========================
# ============================================================
@st.cache_resource
def load_rag_pipeline():
    if not HAS_BACKEND:
        return None
    from healthcare_rag_llm.utils.api_config import APIConfigManager
    api_config_manager = APIConfigManager()
    api_config_default = api_config_manager.get_default_config()
    llm_client = LLMClient(
        api_key=api_config_default.api_key,  # API key
        model="gemini-2.5-flash",
        provider=api_config_default.provider,
        base_url=api_config_default.base_url
    )
    filter_extractor = build_filter_extractor()
    return ResponseGenerator(llm_client,filter_extractor=filter_extractor)

def get_rag_pipeline_lazy():
    """Create the RAG pipeline only when user submits a query."""
    if "rag_pipeline" not in st.session_state:
        st.session_state["rag_pipeline"] = load_rag_pipeline()
    return st.session_state["rag_pipeline"]


def format_evidence_dict(evidence_dict):
    """format evidence_dict as HTML list"""
    if not evidence_dict:
        return "No evidence returned."
    
    html_lines = []
    for i, (key, ev) in enumerate(evidence_dict.items(), 1):
        doc_info = ev.get("doc_info", "Unknown")
        quote = ev.get("quote", "")
        publish_date = ev.get("publish_date", "N/A")
        url = ev.get("url", "N/A")
        
        # 每个 evidence 作为一个列表项
        html_lines.append(f"""
<div style="margin-bottom: 1rem; padding: 0.5rem; border-left: 3px solid #4A90E2;">
<b>{doc_info}, Published on {publish_date}: <a href="{url}" target="_blank" style="color: #4A90E2;">{url}</a></b><br>
{quote}
</div>
        """)
    
    return "".join(html_lines)


_COMPARE_CSS = """
<style>
.chat-row { display: flex; align-items: flex-start; }
.chat-bubble {
    max-width: 95%; padding: 0.7rem 1rem; border-radius: 1rem;
    line-height: 1.6; word-wrap: break-word; box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}
.chat-bubble.assistant {
    background-color: #F4F4F4; border: 1px solid #E0E0E0; color: #000;
    border-top-left-radius: 0.3rem; font-size: 15px;
}
.avatar {
    width: 36px; height: 36px; border-radius: 50%;
    display: flex; align-items: center; justify-content: center;
    font-size: 18px; font-weight: bold; background-color: #E5E7EB; margin: 0 0.5rem;
}
.chat-bubble table { font-size: 14px; border-collapse: collapse; width: 100%; }
.chat-bubble table th { background-color: #E8F0FE; font-weight: 600; }
.chat-bubble table td, .chat-bubble table th {
    padding: 8px 12px; border: 1px solid #D0D0D0; vertical-align: top;
}
</style>
"""

def _wrap_compare_html(content: str) -> str:
    """Wrap compare HTML content with inline CSS for st.html() rendering."""
    return _COMPARE_CSS + content


def format_compare_tables(sections):
    """Render compare definitions result as headline + 2 HTML tables + caveats."""
    headline = html.escape(sections.get("headline_summary", ""))
    policy_def = sections.get("policy_definition", "N/A")
    provider_def = sections.get("provider_manual_definition", "N/A")
    similarities = sections.get("similarities", [])
    differences = sections.get("differences", [])
    caveats = sections.get("caveats")

    table1 = f"""
    <table style="width:100%; border-collapse:collapse; margin:0.8rem 0;">
      <thead>
        <tr style="background:#E8F0FE;">
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Policy Definition</th>
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Provider Manual Definition</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top;">{policy_def}</td>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top;">{provider_def}</td>
        </tr>
      </tbody>
    </table>
    """

    sim_items = "".join(f"<li>{s}</li>" for s in similarities) or "<li>None identified</li>"
    diff_items = "".join(f"<li>{d}</li>" for d in differences) or "<li>None identified</li>"

    table2 = f"""
    <table style="width:100%; border-collapse:collapse; margin:0.8rem 0;">
      <thead>
        <tr style="background:#E8F0FE;">
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Similarities</th>
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Differences</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top;"><ul style="margin:0; padding-left:1.2rem;">{sim_items}</ul></td>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top;"><ul style="margin:0; padding-left:1.2rem;">{diff_items}</ul></td>
        </tr>
      </tbody>
    </table>
    """

    caveats_html = ""
    if caveats:
        caveats_html = f'<p style="color:#856404; background:#FFF3CD; padding:8px 12px; border-radius:4px; margin-top:0.5rem;"><b>Caveats:</b> {html.escape(str(caveats))}</p>'

    return f"""
    <p style="font-weight:600; margin-bottom:0.5rem;">{headline}</p>
    <b>Definitions:</b>
    {table1}
    <b>Comparison:</b>
    {table2}
    {caveats_html}
    """


def format_retrieved_docs(retrieved_docs):
    """format retrieved_docs as HTML list"""
    if not retrieved_docs:
        return ""

    html_lines = []
    for doc in retrieved_docs:
        title = doc.get("title","")
        doc_id = doc.get("doc_id", "Unknown")
        display_name = title if title else doc_id
        url = doc.get("url", "N/A")

        pages = str(doc.get("pages", "N/A"))
        snippet = doc.get("text", "")[:300]
        effective_date = doc.get("effective_date","")

        html_lines.append(f"""
<li style="margin-bottom: 0.5rem;">
<strong>{display_name}</strong> (pages {pages})
<br>
<a href="{url}" target="_blank" style="color: #4A90E2;">{url}</a>
<br>
<span style="color: #666; font-size: 0.9em;">{snippet}...</span>
</li>
        """)

    return "".join(html_lines)

# ============================================================
# ========== CHAT MODE (Multiple Q&A) ========================
# ============================================================
# Initialize history
if "history" not in st.session_state:
    st.session_state["history"] = []  # [{"role": "user"/"assistant", "content": "..."}]

# Container: display history (natural order)
chat_container = st.container()

# ============================================================
# ========== DISPLAY CHAT HISTORY (layout) ===================
# ============================================================
st.markdown(
    """
    <style>
    /* container */
    .chat-container { display: flex; flex-direction: column; gap: 1rem; margin-bottom: 1rem; font-size: 15px; }

    /* chat row */
    .chat-row { display: flex; align-items: flex-start; }
    .chat-row.user { justify-content: flex-end; }

    /* chat bubble */
    .chat-bubble {
        max-width: 70%;
        padding: 0.7rem 1rem;
        border-radius: 1rem;
        line-height: 1.6;
        word-wrap: break-word;
        box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }
    .chat-bubble.assistant {
        background-color: #F4F4F4;
        border: 1px solid #E0E0E0;
        color: #000;
        border-top-left-radius: 0.3rem;
    }
    .chat-bubble.user {
        background-color: #DCF2FF;
        border: 1px solid #CDE9FF;
        color: #000;
        border-top-right-radius: 0.3rem;
    }

    /* avatar */
    .avatar {
        width: 36px; height: 36px;
        border-radius: 50%;
        display: flex; align-items: center; justify-content: center;
        font-size: 18px; font-weight: bold;
        background-color: #E5E7EB;
        margin: 0 0.5rem;
    }
    .avatar.user { background-color: #CDE9FF; }

    /* font */
    input, button, label, div[data-testid="stMarkdownContainer"] {
        font-size: 15px !important;
    }

    /* compare definition tables */
    .chat-bubble table {
        font-size: 14px;
        border-collapse: collapse;
        width: 100%;
    }
    .chat-bubble table th {
        background-color: #E8F0FE;
        font-weight: 600;
    }
    .chat-bubble table td, .chat-bubble table th {
        padding: 8px 12px;
        border: 1px solid #D0D0D0;
        vertical-align: top;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Load history
st.markdown('<div class="chat-container">', unsafe_allow_html=True)
for msg in st.session_state["history"]:
    role = msg["role"]
    text = msg["content"]
    # Convert newlines to <br> for HTML rendering in assistant responses
    if role == "assistant":
        text = text.replace("\n", "<br>")
    evidence_dict = msg.get("evidence_dict", {})
    is_compare = bool(msg.get("is_compare", False))
    compare_sections = msg.get("compare_sections", {})

    if role == "assistant":
        formatted_evidence = format_evidence_dict(evidence_dict)

        # Determine answer body: use tables for compare mode, plain text otherwise
        if is_compare and compare_sections and not compare_sections.get("_parse_failed"):
            answer_body = format_compare_tables(compare_sections)
        else:
            answer_body = text

        if "retrieved_docs" in msg and msg.get("retrieved_docs"):
            formatted_sources = format_retrieved_docs(msg["retrieved_docs"])
            evidence_block = ""
            if not is_compare:
                evidence_block = f"""
<br><br>
<b>Evidence:</b><br>
<em style="color: #666; font-size: 0.9em;">Direct quotes from official documents that support the answer above.</em>
<br>
{formatted_evidence}
<br>
"""

            display_content = f"""
<div class="chat-row assistant">
<div class="avatar assistant">🤔</div>
<div class="chat-bubble assistant">
{answer_body}
{evidence_block}
<strong>📚 Retrieved Sources:</strong><br>
<em style="color: #666; font-size: 0.9em;">Document snippets that were retrieved and analyzed to answer your question.</em>
<ul style="margin-top: 0.5rem; padding-left: 1.5rem;">
{formatted_sources}
</ul>
</div>
</div>
"""
            if is_compare and compare_sections and not compare_sections.get("_parse_failed"):
                st.html(_wrap_compare_html(display_content))
            else:
                st.markdown(display_content, unsafe_allow_html=True)
        else:
            display_content = f"""
<div class="chat-row assistant">
<div class="avatar assistant">🤔</div>
<div class="chat-bubble assistant">
{answer_body}
{"" if is_compare else f"<br><br><b>Evidence:</b><br><em style='color: #666; font-size: 0.9em;'>Direct quotes from official documents that support the answer above.</em><br>{formatted_evidence}"}
</div>
</div>
"""
            if is_compare and compare_sections and not compare_sections.get("_parse_failed"):
                st.html(_wrap_compare_html(display_content))
            else:
                st.markdown(display_content, unsafe_allow_html=True)
    else:
        st.markdown(
            f"""<div class="chat-row user">
                <div class="chat-bubble user">{text}</div>
                <div class="avatar user">👤</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
st.markdown('</div>', unsafe_allow_html=True)

# ============================================================
# ========== FOLLOW-UP QUESTION BUTTONS ======================
# ============================================================
# Show follow-up section only for the last assistant message
if st.session_state["history"]:
    last_msg = st.session_state["history"][-1]
    if last_msg.get("role") == "assistant":
        has_suggestions = bool(last_msg.get("followup_questions"))
        if has_suggestions:
            st.markdown("**Suggested follow-up questions:**")
            cols = st.columns(len(last_msg["followup_questions"]))
            for i, (col, q) in enumerate(zip(cols, last_msg["followup_questions"])):
                with col:
                    if st.button(q, key=f"followup_{i}"):
                        st.session_state["history"].append({"role": "user", "content": q})
                        st.session_state["pending_query"] = q
                        st.session_state["pending_compare"] = False
                        st.session_state["pending_is_followup"] = True
                        st.rerun()

        # Custom follow-up input (with context)
        with st.form("followup_form", clear_on_submit=True):
            followup_query = st.text_input(
                "**Or ask your own follow-up:**",
                placeholder="Type a follow-up question here (keeps conversation context)...",
            )
            followup_submitted = st.form_submit_button("Ask Follow-Up")
        if followup_submitted and followup_query.strip():
            st.session_state["history"].append({"role": "user", "content": followup_query})
            st.session_state["pending_query"] = followup_query
            st.session_state["pending_compare"] = False
            st.session_state["pending_is_followup"] = True
            st.rerun()

# ============================================================
# ========== INPUT AREA (two-line layout) ====================
# ============================================================
with st.container():
    st.markdown('<div class="input-box">', unsafe_allow_html=True)

    with st.form("chat_form", clear_on_submit=True):
        user_query = st.text_input(
            "💬 **Ask a Question:**",
            placeholder="e.g. When did redetermination begin for the COVID-19 Public Health Emergency unwind in New York State?",
        )

        col1, col2, col3 = st.columns([1, 1, 1])
        with col1:
            submitted = st.form_submit_button("📤 Submit", use_container_width=True)
        with col2:
            cleared = st.form_submit_button("🧹 Clear Chat", use_container_width=True)
        with col3:
            compare_submitted = st.form_submit_button("🔍 Compare Definitions", use_container_width=True)

    st.markdown('</div>', unsafe_allow_html=True)

# Clear logic
if cleared:
    st.session_state["history"] = []
    rag_pipeline = st.session_state.get("rag_pipeline")
    if rag_pipeline:
        try:
            rag_pipeline.chat_history.clear()
        except Exception as e:
            st.error(f"Error clearing chat history: {e}")
    st.rerun()

# Submit logic — phase 1: save query and rerun so the user message renders first
if submitted or compare_submitted:
    if not user_query.strip():
        st.warning("Please enter a question before submitting.")
    else:
        # New question from input box → clear previous context
        st.session_state["history"] = [{"role": "user", "content": user_query}]
        rag_pipeline = st.session_state.get("rag_pipeline")
        if rag_pipeline:
            try:
                rag_pipeline.chat_history.clear()
            except Exception:
                pass
        st.session_state["pending_query"] = user_query
        st.session_state["pending_compare"] = bool(compare_submitted)
        st.session_state["pending_is_followup"] = False
        st.rerun()

# Submit logic — phase 2: generate answer (runs on the rerun, user message already visible)
if "pending_query" in st.session_state:
    pending_query = st.session_state.pop("pending_query")
    pending_compare = st.session_state.pop("pending_compare", False)
    pending_is_followup = st.session_state.pop("pending_is_followup", False)
    with st.spinner("Comparing definitions..." if pending_compare else "Retrieving information..."):
        try:
            rag_pipeline = get_rag_pipeline_lazy()
            if rag_pipeline:
                # --- Real backend ---
                history_for_llm = st.session_state["history"] if pending_is_followup else []
                if pending_compare:
                    result = rag_pipeline.answer_compare_definitions(
                        pending_query,
                        concept=pending_query,
                    )
                else:
                    result = rag_pipeline.answer_question(pending_query, history=history_for_llm)
                answer = result.get("answer", "No answer returned.")
                evidence_dict = result.get("evidence_dict", {})
                retrieved_docs = result.get("retrieved_docs", [])
                followup_questions = result.get("followup_questions", [])
                compare_sections = result.get("compare_sections", {})
                if pending_compare and isinstance(retrieved_docs, dict):
                    policy_docs = retrieved_docs.get("policy", []) or []
                    provider_docs = retrieved_docs.get("provider_manual", []) or []
                    retrieved_docs = policy_docs + provider_docs
            else:
                # --- Mock mode ---
                answer = (
                    "⚠️ Mock mode: Backend not connected.\n"
                    "No grounded answer can be generated. "
                    "Please connect the backend (RAG pipeline) to enable cited answers."
                )
                evidence_dict = {}
                retrieved_docs = []
                followup_questions = []
            st.session_state["history"].append({
                                                    "role": "assistant",
                                                    "content": answer,
                                                    "evidence_dict": evidence_dict,
                                                    "retrieved_docs": retrieved_docs,
                                                    "is_compare": pending_compare,
                                                    "compare_sections": compare_sections if pending_compare else {},
                                                    "followup_questions": followup_questions,
                                                })
            st.rerun()

        except Exception as e:
            st.session_state["history"].pop()  # remove orphaned user message
            st.error(f"Error: {e}")


# ============================================================
# ========== BACKEND MEMORY VIEWER (for debugging) ===========
# ============================================================

# if rag_pipeline and hasattr(rag_pipeline, "chat_history"):
#     with st.expander("🧠 Backend Memory Viewer", expanded=False):
#         if hasattr(rag_pipeline.chat_history, "messages"):
#             messages = rag_pipeline.chat_history.get_messages()
#             if not messages:
#                 st.caption("*(Empty – no conversation stored in backend memory)*")
#             else:
#                 for i, msg in enumerate(messages, 1):
#                     role = msg["role"].capitalize()
#                     content = msg["content"][:1000]  # 截断长文本防止爆页面
#                     st.markdown(f"**{i}. {role}:** {content}")
#         else:
#             st.caption("ChatHistory not initialized or has no messages attribute.")

# # ============================================================
# # ========== FOOTER ==========================================
# # ============================================================
# st.divider()
# st.markdown(
#     "<p style='font-size: small; color: gray;'>© 2025 Columbia DSI x KPMG | For educational use only.</p>",
#     unsafe_allow_html=True
# )
