import streamlit as st
from PIL import Image
from pathlib import Path
import sys
import traceback
import html
import markdown
import re
from datetime import date, datetime

# ============================================================
# ========== PATH SETUP ======================================
# ============================================================
st.set_page_config(page_title="Compare Definitions - NYS Policies Assistant", layout="wide")

ROOT = Path(__file__).resolve().parents[2]  # project root
SRC_DIR = ROOT / "src"
sys.path.append(str(SRC_DIR))  # allow import from src/

# ============================================================
# ========== IMPORT PIPELINE MODULES =========================
# ============================================================
try:
    from healthcare_rag_llm.llm.llm_client import LLMClient
    from healthcare_rag_llm.llm.response_generator import ResponseGenerator
    from healthcare_rag_llm.filters.load_metadata import build_filter_extractor
    HAS_BACKEND = True
except Exception as e:
    HAS_BACKEND = False
    st.exception(e)
    st.code(traceback.format_exc())
    st.warning(f"⚠️ Backend import failed: {e}. Mock mode enabled.")

# ============================================================
# ========== HEADER ==========================================
# ============================================================
ROOT_DIR = Path(__file__).parent.parent
ASSETS_DIR = ROOT_DIR / "assets"
nys_logo_path = ASSETS_DIR / "nys_logo.png"

col1, col2 = st.columns([5, 1])
with col1:
    st.title("Compare Definitions")
    st.caption("Side-by-side comparison of definitions across policy and provider manual documents.")
with col2:
    if nys_logo_path.exists():
        nys_logo = Image.open(nys_logo_path)
        st.image(nys_logo, width=200)
    else:
        st.text("NYS Logo Missing")

# ============================================================
# ========== DISCLAIMER ======================================
# ============================================================
with st.expander("📜 Disclaimer", expanded=True):
    st.markdown("""
This assistant is part of the **Columbia University x KPMG Capstone Project**:
*Intelligent Document Analysis for Healthcare Programs Using LLMs and RAG.*

The responses are generated by an AI model referencing official
New York State Medicaid documents and related authorities.
They do not constitute legal advice.
""")

with st.expander("ℹ️ About and How It Works", expanded=True):
    st.markdown("""
**Purpose (Comparison)**  
Compare how a concept is defined in policy vs provider manuals.

**How it works**  
We retrieve both sources and generate a cited side-by-side comparison.

**Tips**  
Use a concise concept (e.g., "medical necessity") and add qualifiers if needed.
""")

# ============================================================
# ========== INITIALIZE RAG PIPELINE =========================
# ============================================================
@st.cache_resource
def load_rag_pipeline():
    if not HAS_BACKEND:
        return None
    from healthcare_rag_llm.utils.api_config import APIConfigManager
    api_config_manager = APIConfigManager()
    api_config_default = api_config_manager.get_default_config()
    llm_client = LLMClient(
        api_key=api_config_default.api_key,
        model="gemini-2.5-flash",
        provider=api_config_default.provider,
        base_url=api_config_default.base_url
    )
    filter_extractor = build_filter_extractor()
    return ResponseGenerator(llm_client, filter_extractor=filter_extractor)

def get_rag_pipeline_lazy():
    # Delay backend startup until the first real query to keep page load fast.
    if "compare_rag_pipeline" not in st.session_state:
        st.session_state["compare_rag_pipeline"] = load_rag_pipeline()
    return st.session_state["compare_rag_pipeline"]

# ============================================================
# ========== HELPERS =========================================
# ============================================================
def format_evidence_dict(evidence_dict):
    if not evidence_dict:
        return "No evidence returned."
    html_lines = []
    for _, ev in evidence_dict.items():
        doc_info = html.escape(str(ev.get("doc_info", "Unknown")))
        quote = html.escape(str(ev.get("quote", ""))).replace("\n", "<br>")
        publish_date = html.escape(str(ev.get("publish_date", "N/A")))
        url = html.escape(str(ev.get("url", "N/A")))
        html_lines.append(
            "<li>"
            f"<strong>{doc_info}</strong>, Published on {publish_date}: "
            f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\">{url}</a>"
            f"<div style=\"margin-top:0.35rem; padding-left:0.75rem; border-left:3px solid #E0E0E0; color:#333;\">{quote}</div>"
            "</li>"
        )
    return "\n".join(html_lines)

def format_retrieved_docs(retrieved_docs):
    if not retrieved_docs:
        return ""
    html_lines = []
    for doc in retrieved_docs:
        title = html.escape(str(doc.get("title", "")))
        doc_id = html.escape(str(doc.get("doc_id", "Unknown")))
        display_name = title if title else doc_id
        url = html.escape(str(doc.get("url", "N/A")))
        pages = html.escape(str(doc.get("pages", "N/A")))
        snippet = html.escape(str(doc.get("text", ""))[:300]).replace("\n", " ")
        html_lines.append(
            "<li>"
            f"<strong>{display_name}</strong> (pages {pages})<br>"
            f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\">{url}</a><br>"
            f"<span style=\"color:#666; font-size:0.9em;\">{snippet}...</span>"
            "</li>"
        )
    return "\n".join(html_lines)


def format_retrieved_docs_compare_table(retrieved_docs_grouped):
    """Render compare retrieved docs as a 2-column table: provider manual vs Medicaid Update."""
    policy_docs = retrieved_docs_grouped.get("policy", []) or []
    provider_docs = retrieved_docs_grouped.get("provider_manual", []) or []

    def _docs_to_ul(docs):
        if not docs:
            return "<em style='color:#666; font-size:0.9em;'>No sources retrieved.</em>"

        items = []
        for doc in docs:
            title = html.escape(str(doc.get("title", "")))
            doc_id = html.escape(str(doc.get("doc_id", "Unknown")))
            display_name = title if title else doc_id
            url = html.escape(str(doc.get("url", "N/A")))
            pages = html.escape(str(doc.get("pages", "N/A")))
            snippet = html.escape(str(doc.get("text", ""))[:280]).replace("\n", " ")
            items.append(
                "<li>"
                f"<strong>{display_name}</strong> (pages {pages})<br>"
                f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"word-break:break-all; overflow-wrap:anywhere;\">{url}</a><br>"
                f"<span style=\"color:#666; font-size:0.9em; word-break:break-word; overflow-wrap:anywhere;\">{snippet}...</span>"
                "</li>"
            )
        return f"<ul style='margin:0; padding-left:1.1rem; word-break:break-word; overflow-wrap:anywhere;'>{''.join(items)}</ul>"

    policy_html = _docs_to_ul(policy_docs)
    provider_html = _docs_to_ul(provider_docs)

    return f"""
    <div style="width:100%; overflow-x:auto;">
    <table style="width:100%; border-collapse:collapse; margin:0.6rem 0 0.2rem 0; table-layout:fixed;">
      <thead>
        <tr style="background:#E8F0FE; color:#333;">
          <th style="padding:8px 12px; border:1px solid #D0D0D0; width:50%; text-align:left;">Provider Manual Sources</th>
          <th style="padding:8px 12px; border:1px solid #D0D0D0; width:50%; text-align:left;">Medicaid Update Sources</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #D0D0D0; vertical-align:top; word-break:break-word; overflow-wrap:anywhere; color:#333;">{provider_html}</td>
          <td style="padding:8px 12px; border:1px solid #D0D0D0; vertical-align:top; word-break:break-word; overflow-wrap:anywhere; color:#333;">{policy_html}</td>
        </tr>
      </tbody>
    </table>
    </div>
    """

_COMPARE_CSS = """
<style>
.chat-row { display: flex; align-items: flex-start; }
.chat-bubble {
    max-width: 95%; padding: 0.7rem 1rem; border-radius: 1rem;
    line-height: 1.6; word-wrap: break-word; box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}
.chat-bubble.assistant {
    background-color: #F4F4F4; border: 1px solid #E0E0E0; color: #000;
    border-top-left-radius: 0.3rem; font-size: 15px;
}
.avatar {
    width: 36px; height: 36px; border-radius: 50%;
    display: flex; align-items: center; justify-content: center;
    font-size: 18px; font-weight: bold; background-color: #E5E7EB; margin: 0 0.5rem;
}
.chat-bubble table { font-size: 14px; border-collapse: collapse; width: 100%; }
.chat-bubble table th { background-color: #E8F0FE; font-weight: 600; }
.chat-bubble table td, .chat-bubble table th {
    padding: 8px 12px; border: 1px solid #D0D0D0; vertical-align: top;
}
.chat-bubble table td, .chat-bubble table th, .chat-bubble a, .chat-bubble li, .chat-bubble span {
    word-break: break-word;
    overflow-wrap: anywhere;
}
</style>
"""

def _wrap_compare_html(content: str) -> str:
    """Wrap compare HTML content with inline CSS for st.html() rendering."""
    return _COMPARE_CSS + content


def markdown_to_html(md_text: str) -> str:
    """Convert answer markdown to HTML with light normalization for list rendering."""
    if not md_text:
        return ""
    # Follow-up answers often come back as inline bullets, so normalize them first.
    normalized_md = re.sub(r"(?im)^answer\s*:?\s*", "", md_text, count=1).strip()
    # Force inline bullet patterns to become actual markdown lists.
    normalized_md = re.sub(r" \* ", "\n\n- ", normalized_md)
    normalized_md = re.sub(r"(?m)^\s*\*\s+", "- ", normalized_md)
    return markdown.markdown(normalized_md, extensions=["extra", "sane_lists"])


def _parse_effective_date(value):
    """Best-effort parse for document effective dates used in compare rendering."""
    if not value:
        return None
    if isinstance(value, date) and not isinstance(value, datetime):
        return value
    if isinstance(value, datetime):
        return value.date()
    raw = str(value).strip()
    if not raw or raw.upper() == "N/A":
        return None
    for parser in (
        lambda s: datetime.fromisoformat(s).date(),
        lambda s: datetime.strptime(s, "%Y-%m-%d").date(),
        lambda s: datetime.strptime(s, "%B %Y").date(),
        lambda s: datetime.strptime(s, "%b %Y").date(),
        lambda s: datetime.strptime(s, "%B %d, %Y").date(),
        lambda s: datetime.strptime(s, "%b %d, %Y").date(),
    ):
        try:
            return parser(raw)
        except ValueError:
            continue
    return None


def _effective_date_label(doc):
    return html.escape(str(doc.get("effective_date") or "N/A"))


def _doc_display_name(doc):
    title = str(doc.get("title", "")).strip()
    doc_id = str(doc.get("doc_id", "")).strip()
    return title or doc_id or "Unknown Document"


def _latest_doc(docs):
    dated_docs = []
    for doc in docs or []:
        parsed = _parse_effective_date(doc.get("effective_date"))
        if parsed is not None:
            dated_docs.append((parsed, doc))
    if not dated_docs:
        return None
    dated_docs.sort(key=lambda item: item[0], reverse=True)
    return dated_docs[0][1]


def _build_recency_summary(retrieved_docs_grouped):
    """Create a visible recency summary from retrieved policy/provider sources."""
    policy_latest = _latest_doc(retrieved_docs_grouped.get("policy", []))
    provider_latest = _latest_doc(retrieved_docs_grouped.get("provider_manual", []))

    if not policy_latest and not provider_latest:
        return (
            "Recency could not be determined from the retrieved sources because no usable "
            "effective dates were available."
        )

    parts = []
    if policy_latest:
        parts.append(
            f"Newest policy source: {_doc_display_name(policy_latest)} "
            f"(effective date: {_effective_date_label(policy_latest)})."
        )
    else:
        parts.append("Newest policy source: effective date unavailable from the retrieved policy sources.")

    if provider_latest:
        parts.append(
            f"Newest provider manual source: {_doc_display_name(provider_latest)} "
            f"(effective date: {_effective_date_label(provider_latest)})."
        )
    else:
        parts.append("Newest provider manual source: effective date unavailable from the retrieved provider manual sources.")

    policy_date = _parse_effective_date(policy_latest.get("effective_date")) if policy_latest else None
    provider_date = _parse_effective_date(provider_latest.get("effective_date")) if provider_latest else None

    if policy_date and provider_date:
        if policy_date > provider_date:
            parts.append("Overall, the policy source is more up to date and should carry more weight for current guidance.")
        elif provider_date > policy_date:
            parts.append("Overall, the provider manual source is more up to date and should carry more weight for current guidance.")
        else:
            parts.append("Overall, the newest policy and provider manual sources are tied on effective date.")
    else:
        parts.append("Overall recency across source types cannot be fully determined because one or both effective dates are unavailable.")

    return " ".join(parts)


def format_compare_tables(sections, retrieved_docs_grouped=None):
    """Render compare definitions result as headline + 2 HTML tables + caveats."""
    headline = html.escape(sections.get("headline_summary", ""))
    policy_def = sections.get("policy_definition", "N/A")
    provider_def = sections.get("provider_manual_definition", "N/A")
    similarities = sections.get("similarities", [])
    differences = sections.get("differences", [])
    caveats = sections.get("caveats")
    retrieved_docs_grouped = retrieved_docs_grouped or {}

    citation_to_num = {}
    citation_order = []
    known_docs = {}

    for docs in retrieved_docs_grouped.values():
        for doc in docs or []:
            display_name = _doc_display_name(doc)
            known_docs[display_name] = doc
            doc_id = str(doc.get("doc_id", "")).strip()
            if doc_id:
                known_docs[doc_id] = doc

    def _match_doc_for_citation(cite: str):
        cleaned = str(cite or "").strip()
        if not cleaned:
            return None
        best_match = None
        best_len = -1
        for candidate, doc in known_docs.items():
            candidate = str(candidate or "").strip()
            if not candidate:
                continue
            if cleaned == candidate or cleaned.startswith(candidate + ":") or cleaned.startswith(candidate + " —") or cleaned.startswith(candidate + " â€”"):
                if len(candidate) > best_len:
                    best_match = doc
                    best_len = len(candidate)
        return best_match

    def _date_from_citation_text(cite: str) -> str:
        cleaned = str(cite or "").strip()
        if not cleaned:
            return "N/A"
        for sep in (" — ", " â€” "):
            if sep in cleaned:
                tail = cleaned.rsplit(sep, 1)[1].strip()
                if _parse_effective_date(tail):
                    return html.escape(tail)
        return "N/A"

    def _strip_trailing_date_from_citation(cite: str) -> str:
        cleaned = str(cite or "").strip()
        if not cleaned:
            return ""
        for sep in (" â€” ", " Ã¢â‚¬â€ "):
            if sep in cleaned:
                head, tail = cleaned.rsplit(sep, 1)
                if _parse_effective_date(tail.strip()):
                    return head.strip()
        return cleaned

    def _normalize_text_with_inline_numbers(text: str) -> str:
        # Replace raw inline citation strings with stable numeric references like [1].
        if text is None:
            return ""
        raw = str(text)

        def _is_valid_citation_text(cite: str) -> bool:
            cleaned = re.sub(r"\s+", " ", (cite or "")).strip()
            if not cleaned:
                return False
            if cleaned in {"...", "..", "."}:
                return False
            if re.fullmatch(r"[\.\,\;\:\-\u2013\u2014\s]+", cleaned):
                return False
            if len(re.sub(r"[\W_]+", "", cleaned)) < 3:
                return False
            return True
        
        def _replace_citation(match):
            cite = match.group(1).strip()
            if not _is_valid_citation_text(cite):
                return ""
            if cite not in citation_to_num:
                citation_to_num[cite] = len(citation_order) + 1
                citation_order.append(cite)
            n = citation_to_num[cite]
            return f" [{n}]"

        normalized = re.sub(r"\[([^\[\]]+)\]", _replace_citation, raw)
        normalized = re.sub(r"\s{2,}", " ", normalized).strip()
        return html.escape(normalized)

    policy_def_html = _normalize_text_with_inline_numbers(policy_def)
    provider_def_html = _normalize_text_with_inline_numbers(provider_def)
    sim_items_html = "".join(
        f"<li>{_normalize_text_with_inline_numbers(s)}</li>" for s in similarities
    ) or "<li>None identified</li>"
    diff_items_html = "".join(
        f"<li>{_normalize_text_with_inline_numbers(d)}</li>" for d in differences
    ) or "<li>None identified</li>"

    table1 = f"""
    <table style="width:100%; border-collapse:collapse; margin:0.8rem 0;">
      <thead>
        <tr style="background:#E8F0FE; color:#333;">
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Provider Manual Definition</th>
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Medicaid Update Definition</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;">{provider_def_html}</td>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;">{policy_def_html}</td>
        </tr>
      </tbody>
    </table>
    """

    table2 = f"""
    <table style="width:100%; border-collapse:collapse; margin:0.8rem 0;">
      <thead>
        <tr style="background:#E8F0FE; color:#333;">
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Similarities</th>
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Differences</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;"><ul style="margin:0; padding-left:1.2rem;">{sim_items_html}</ul></td>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;"><ul style="margin:0; padding-left:1.2rem;">{diff_items_html}</ul></td>
        </tr>
      </tbody>
    </table>
    """

    caveats_html = ""
    if caveats:
        caveats_html = f'<p style="color:#856404; background:#FFF3CD; padding:8px 12px; border-radius:4px; margin-top:0.5rem;"><b>Caveats:</b> {html.escape(str(caveats))}</p>'


    references_html = ""
    if citation_order:
        ref_items = []
        for i, cite in enumerate(citation_order, 1):
            base = cite.split("—", 1)[0].strip()
            base_name = base.split(":", 1)[0].strip()
            matched_doc = _match_doc_for_citation(cite)
            effective_label = _effective_date_label(matched_doc) if matched_doc else _date_from_citation_text(cite)
            display_cite = re.sub(r"\s*[-\u2013\u2014]\s*\d{4}-\d{2}-\d{2}\s*$", "", str(cite)).strip()
            ref_items.append(
                f"<li>[{i}] {html.escape(display_cite)}"
                f"<div style='color:#666; font-size:0.9em;'>Effective date: {effective_label}</div></li>"
            )
        references_html = (
            "<b>References:</b>"
            f"<ol style='margin-top:0.5rem; padding-left:1.4rem;'>{''.join(ref_items)}</ol>"
        )

    recency_summary = html.escape(_build_recency_summary(retrieved_docs_grouped))
    recency_html = (
        "<div style='margin-bottom:0.8rem; padding:10px 12px; background:#EEF6FF; "
        "color:#333; border:1px solid #CFE3FF; border-radius:8px;'>"
        "<b>Most Up-To-Date Source Signal:</b> "
        f"{recency_summary}"
        "</div>"
    )

    return f"""
    {recency_html}
    <p style="font-weight:600; margin-bottom:0.5rem;">{headline}</p>
    <b>Definitions:</b>
    {table1}
    <b>Comparison:</b>
    {table2}
    {references_html}
    {caveats_html}
    """


# ============================================================
# ========== SESSION STATE ===================================
# ============================================================
if "compare_history" not in st.session_state:
    st.session_state["compare_history"] = []

# ============================================================
# ========== DISPLAY HISTORY ================================
# ============================================================
st.markdown(
    """
    <style>
    .chat-container { display: flex; flex-direction: column; gap: 1rem; margin-bottom: 1rem; font-size: 15px; }
    .chat-row { display: flex; align-items: flex-start; }
    .chat-row.user { justify-content: flex-end; }
    .chat-bubble {
        max-width: 70%;
        padding: 0.7rem 1rem;
        border-radius: 1rem;
        line-height: 1.6;
        word-wrap: break-word;
        box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }
    .chat-bubble.assistant {
        background-color: #F4F4F4;
        border: 1px solid #E0E0E0;
        color: #000 !important;
        border-top-left-radius: 0.3rem;
    }
    .chat-bubble.assistant * {
        color: #000 !important;
    }
    .chat-bubble.assistant a {
        color: #1a6dd4 !important;
    }
    .chat-bubble.user {
        background-color: #DCF2FF;
        border: 1px solid #CDE9FF;
        color: #000 !important;
        border-top-right-radius: 0.3rem;
    }
    .chat-bubble.user * {
        color: #000 !important;
    }
    .avatar {
        width: 36px; height: 36px;
        border-radius: 50%;
        display: flex; align-items: center; justify-content: center;
        font-size: 18px; font-weight: bold;
        background-color: #E5E7EB;
        margin: 0 0.5rem;
    }
    .avatar.user { background-color: #CDE9FF; }
    input, button, label, div[data-testid="stMarkdownContainer"] {
        font-size: 15px !important;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown('<div class="chat-container">', unsafe_allow_html=True)
for msg in st.session_state["compare_history"]:
    role = msg["role"]
    text = msg["content"]

    if role == "assistant":
        evidence_dict = msg.get("evidence_dict", {})
        formatted_evidence = format_evidence_dict(evidence_dict)
        retrieved_docs = msg.get("retrieved_docs", [])
        retrieved_docs_grouped = msg.get("retrieved_docs_grouped", {})
        formatted_sources = format_retrieved_docs(retrieved_docs) if retrieved_docs else ""
        compare_sections = msg.get("compare_sections", {})
        is_followup = bool(msg.get("is_followup", False))

        answer_body = text
        answer_body_is_html = False
        # Render as custom HTML tables whenever valid compare_sections are available.
        if compare_sections and not compare_sections.get("_parse_failed"):
            answer_body = format_compare_tables(compare_sections, retrieved_docs_grouped=retrieved_docs_grouped)
            answer_body_is_html = True

        answer_body_html = answer_body if answer_body_is_html else markdown_to_html(answer_body)

        has_grouped_sources = bool(retrieved_docs_grouped) and (
            bool(retrieved_docs_grouped.get("policy")) or bool(retrieved_docs_grouped.get("provider_manual"))
        )
        has_sources = bool(retrieved_docs) or has_grouped_sources

        if is_followup and not answer_body_is_html:
            # Fallback: follow-ups without valid compare_sections render as plain markdown.
            st.markdown(
                """
<div class="chat-row assistant">
<div class="avatar assistant">&#x1F914;</div>
<div class="chat-bubble assistant">
                """,
                unsafe_allow_html=True,
            )
            st.markdown("**Answer:**")
            display_text = text.strip()
            display_text = re.sub(r"^answer\s*:?\s*", "", display_text, count=1, flags=re.IGNORECASE).strip()
            display_text = re.sub(r" \* ", "\n- ", display_text)
            display_text = re.sub(r"(?m)^\s*\*\s+", "- ", display_text)
            display_text = re.sub(r" \- (?=[A-Za-z0-9\"'])", "\n- ", display_text)
            st.markdown(display_text)
            if evidence_dict:
                st.markdown("")
                st.markdown("**Evidence:**")
                st.markdown("_Direct quotes from official documents that support the answer above._")
                st.markdown(
                    f"<ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_evidence}</ul>",
                    unsafe_allow_html=True,
                )
            if has_sources:
                st.markdown("")
                st.markdown("**Retrieved Sources:**")
                st.markdown("_Document snippets that were retrieved and analyzed to answer your question._")
                st.markdown(
                    f"<ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_sources}</ul>",
                    unsafe_allow_html=True,
                )
            st.markdown("</div></div>", unsafe_allow_html=True)
        else:
            if has_sources:
                if has_grouped_sources:
                    # Initial compare results keep policy/provider sources separated side by side.
                    retrieved_sources_html = (
                        "<strong>&#x1F4DA; Retrieved Sources:</strong><br>"
                        "<em style=\"color: #666; font-size: 0.9em;\">Policy sources are on the left; provider manual sources are on the right.</em>"
                        + format_retrieved_docs_compare_table(retrieved_docs_grouped)
                    )
                else:
                    retrieved_sources_html = f"""
<strong>&#x1F4DA; Retrieved Sources:</strong><br>
<em style="color: #666; font-size: 0.9em;">Document snippets that were retrieved and analyzed to answer your question.</em>
<ul style="margin-top: 0.5rem; padding-left: 1.5rem;">
{formatted_sources}
</ul>
"""
                display_content = f"""
<div class="chat-row assistant">
<div class="avatar assistant">&#x1F914;</div>
<div class="chat-bubble assistant">
{answer_body_html}
{"<br><br><b>Evidence:</b><br><em style='color: #666; font-size: 0.9em;'>Direct quotes from official documents that support the answer above.</em><ul style='margin-top:0.5rem; padding-left:1.5rem;'>" + formatted_evidence + "</ul>" if evidence_dict else ""}
{retrieved_sources_html}
</div>
</div>
"""
            else:
                display_content = f"""
<div class="chat-row assistant">
<div class="avatar assistant">&#x1F914;</div>
<div class="chat-bubble assistant">
{answer_body_html}
{"" if not evidence_dict else f"<br><br><b>Evidence:</b><br><em style='color: #666; font-size: 0.9em;'>Direct quotes from official documents that support the answer above.</em><ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_evidence}</ul>"}
</div>
</div>
"""
            if compare_sections and not compare_sections.get("_parse_failed"):
                st.html(_wrap_compare_html(display_content))
            else:
                st.markdown(display_content, unsafe_allow_html=True)
    else:
        safe_text = html.escape(text)
        st.markdown(
            f"""<div class="chat-row user">
                <div class="chat-bubble user">{safe_text}</div>
                <div class="avatar user">&#x1F464;</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
st.markdown('</div>', unsafe_allow_html=True)

# ============================================================
# ========== FOLLOW-UP QUESTION BUTTONS ======================
# ============================================================
is_generating_compare = "compare_pending_query" in st.session_state

if (not is_generating_compare) and st.session_state["compare_history"]:
    last_msg = st.session_state["compare_history"][-1]
    if last_msg.get("role") == "assistant":
        has_suggestions = bool(last_msg.get("followup_questions"))
        if has_suggestions:
            st.markdown("**Suggested follow-up questions:**")
            cols = st.columns(len(last_msg["followup_questions"]))
            for i, (col, q) in enumerate(zip(cols, last_msg["followup_questions"])):
                with col:
                    if st.button(q, key=f"compare_followup_{i}"):
                        # Button clicks do not answer immediately; they queue work for the next rerun.
                        st.session_state["compare_history"].append({"role": "user", "content": q})
                        st.session_state["compare_pending_query"] = q
                        st.session_state["compare_pending_is_followup"] = True
                        st.rerun()


# ============================================================
# ========== INPUT AREA ======================================
# ============================================================
submitted = False
followup_submitted = False
cleared = False

if not is_generating_compare:
    with st.container():
        st.markdown('<div class="input-box">', unsafe_allow_html=True)

        with st.form("compare_form", clear_on_submit=True):
            user_query = st.text_input(
                "🔎 **Compare a Concept:**",
                placeholder="e.g. Define 'medical necessity' in policy vs provider manual.",
            )

            has_assistant_response = any(
                msg.get("role") == "assistant" for msg in st.session_state["compare_history"]
            )

            if has_assistant_response:
                col1, col2 = st.columns([1, 1])
                with col1:
                    followup_submitted = st.form_submit_button("↪️ Ask Follow-Up", use_container_width=True)
                with col2:
                    cleared = st.form_submit_button("🧹 Clear", use_container_width=True)
            else:
                submitted = st.form_submit_button("🔍 Compare", use_container_width=True)

        st.markdown('</div>', unsafe_allow_html=True)

# ============================================================
# ========== CLEAR / SUBMIT ==================================
# ============================================================
if cleared:
    st.session_state["compare_history"] = []
    rag_pipeline = st.session_state.get("compare_rag_pipeline")
    if rag_pipeline:
        try:
            rag_pipeline.chat_history.clear()
        except Exception as e:
            st.error(f"Error clearing chat history: {e}")
    st.rerun()

# Submit logic ? phase 1
if submitted:
    if not user_query.strip():
        st.warning("Please enter a concept before comparing.")
    else:
        # A brand-new compare query resets the conversation to a fresh compare session.
        st.session_state["compare_history"] = [{"role": "user", "content": user_query}]
        rag_pipeline = st.session_state.get("compare_rag_pipeline")
        if rag_pipeline:
            try:
                rag_pipeline.chat_history.clear()
            except Exception:
                pass
        st.session_state["compare_pending_query"] = user_query
        st.session_state["compare_pending_is_followup"] = False
        st.rerun()

if followup_submitted:
    if not user_query.strip():
        st.warning("Please enter a follow-up question before submitting.")
    else:
        # Follow-ups extend the current conversation instead of clearing it.
        st.session_state["compare_history"].append({"role": "user", "content": user_query})
        st.session_state["compare_pending_query"] = user_query
        st.session_state["compare_pending_is_followup"] = True
        st.rerun()

# Submit logic — phase 2
if "compare_pending_query" in st.session_state:
    pending_query = st.session_state.pop("compare_pending_query")
    pending_is_followup = st.session_state.pop("compare_pending_is_followup", False)
    # Streamlit reruns the whole file after every interaction; this block is the "do the work now" phase.
    with st.spinner("Retrieving information..." if pending_is_followup else "Comparing definitions..."):
        try:
            rag_pipeline = get_rag_pipeline_lazy()
            if rag_pipeline:
                # Both initial compare and follow-ups use the compare endpoint
                # so the response always renders as the side-by-side table format.
                result = rag_pipeline.answer_compare_definitions(
                    pending_query,
                    concept=pending_query,
                )
                answer = result.get("answer", "No answer returned.")
                evidence_dict = result.get("evidence_dict", {})
                retrieved_docs = result.get("retrieved_docs", [])
                retrieved_docs_grouped = {}
                followup_questions = result.get("followup_questions", [])
                compare_sections = result.get("compare_sections", {})
                if isinstance(retrieved_docs, dict):
                    # Preserve the split source groups for the side-by-side retrieved source table.
                    policy_docs = retrieved_docs.get("policy", []) or []
                    provider_docs = retrieved_docs.get("provider_manual", []) or []
                    retrieved_docs_grouped = {
                        "policy": policy_docs,
                        "provider_manual": provider_docs,
                    }
                    retrieved_docs = policy_docs + provider_docs
            else:
                answer = (
                    "Mock mode: Backend not connected.\n"
                    "No grounded answer can be generated. "
                    "Please connect the backend (RAG pipeline) to enable cited answers."
                )
                evidence_dict = {}
                retrieved_docs = []
                retrieved_docs_grouped = {}
                followup_questions = []
                compare_sections = {}
            st.session_state["compare_history"].append({
                "role": "assistant",
                "content": answer,
                "evidence_dict": evidence_dict,
                "retrieved_docs": retrieved_docs,
                "retrieved_docs_grouped": retrieved_docs_grouped,
                "compare_sections": compare_sections,
                "followup_questions": followup_questions,
                "is_followup": pending_is_followup,
            })
            st.rerun()
        except Exception as e:
            st.session_state["compare_history"].pop()
            st.error(f"Error: {e}")
