import streamlit as st
from PIL import Image
from pathlib import Path
import sys
import traceback
import html
import json
import markdown
import re
import threading
import uuid
from datetime import date, datetime

# ============================================================
# ========== PATH SETUP ======================================
# ============================================================
st.set_page_config(page_title="Compare Definitions - NYS Policies Assistant", layout="wide")

ROOT = Path(__file__).resolve().parents[2]  # project root
SRC_DIR = ROOT / "src"
sys.path.append(str(SRC_DIR))  # allow import from src/

# ============================================================
# ========== IMPORT PIPELINE MODULES =========================
# ============================================================
try:
    from healthcare_rag_llm.llm.llm_client import GenerationCancelled
    from healthcare_rag_llm.llm.llm_client import LLMClient
    from healthcare_rag_llm.llm.response_generator import ResponseGenerator
    from healthcare_rag_llm.filters.load_metadata import build_filter_extractor
    HAS_BACKEND = True
except Exception as e:
    HAS_BACKEND = False
    st.exception(e)
    st.code(traceback.format_exc())
    st.warning(f"⚠️ Backend import failed: {e}. Mock mode enabled.")

# ============================================================
# ========== HEADER ==========================================
# ============================================================
ROOT_DIR = Path(__file__).parent.parent
ASSETS_DIR = ROOT_DIR / "assets"
nys_logo_path = ASSETS_DIR / "nys_logo.png"

col1, col2 = st.columns([5, 1])
with col1:
    st.title("Compare Definitions")
    st.caption("Side-by-side comparison of definitions across policy and provider manual documents.")
with col2:
    if nys_logo_path.exists():
        nys_logo = Image.open(nys_logo_path)
        st.image(nys_logo, width=200)
    else:
        st.text("NYS Logo Missing")

# ============================================================
# ========== DISCLAIMER ======================================
# ============================================================
with st.expander("📜 Disclaimer", expanded=True):
    st.markdown("""
This assistant is part of the **Columbia University x KPMG Capstone Project**:
*Intelligent Document Analysis for Healthcare Programs Using LLMs and RAG.*

The responses are generated by an AI model referencing official
New York State Medicaid documents and related authorities.
They do not constitute legal advice.
""")

with st.expander("ℹ️ About and How It Works", expanded=True):
    st.markdown("""
**Purpose (Comparison)**  
Compare how a concept is defined in policy vs provider manuals.

**How it works**  
We retrieve both sources and generate a cited side-by-side comparison.

**Tips**  
Use a concise concept (e.g., "medical necessity") and add qualifiers if needed.
    """)

compare_status_notice = st.session_state.pop("compare_status_notice", None)
if compare_status_notice:
    st.info(compare_status_notice)

compare_status_error = st.session_state.pop("compare_status_error", None)
if compare_status_error:
    st.error(f"Error: {compare_status_error}")

# ============================================================
# ========== INITIALIZE RAG PIPELINE =========================
# ============================================================
@st.cache_resource
def load_rag_pipeline():
    if not HAS_BACKEND:
        return None
    from healthcare_rag_llm.utils.api_config import APIConfigManager
    api_config_manager = APIConfigManager()
    api_config_default = api_config_manager.get_default_config()
    provider = (api_config_default.provider or "").lower()
    provider_to_model = {
        "deepseek": "deepseek-chat",
        "gemini": "gemini-2.5-flash",
        # Use a widely available OpenAI-compatible fallback.
        "openai": "gpt-4o-mini",
    }
    model = provider_to_model.get(provider, "deepseek-chat")
    llm_client = LLMClient(
        api_key=api_config_default.api_key,
        model=model,
        provider=api_config_default.provider,
        base_url=api_config_default.base_url
    )
    filter_extractor = build_filter_extractor()
    return ResponseGenerator(llm_client, filter_extractor=filter_extractor)

def get_rag_pipeline_lazy():
    # Delay backend startup until the first real query to keep page load fast.
    if "compare_rag_pipeline" not in st.session_state:
        st.session_state["compare_rag_pipeline"] = load_rag_pipeline()
    return st.session_state["compare_rag_pipeline"]


@st.cache_resource
def _get_compare_task_store():
    # This is the "job board" for Compare mode.
    # It does NOT store compare chat history.
    # It only stores temporary state for comparisons that are currently running.
    return {"tasks": {}, "lock": threading.Lock()}


def _snapshot_compare_task(task_id: str):
    # Read the current state of one running compare job.
    # The UI uses this to check whether the comparison is still running or was cancelled.
    store = _get_compare_task_store()
    tasks = store["tasks"]
    lock = store["lock"]
    with lock:
        task = tasks.get(task_id)
        if not task:
            return None
        return dict(task)


def _set_compare_task_fields(task_id: str, **fields):
    # Update part of one compare job record.
    # Example uses:
    # - mark stop as requested
    # - mark the compare job completed
    # - save an error message for that job
    store = _get_compare_task_store()
    tasks = store["tasks"]
    lock = store["lock"]
    with lock:
        task = tasks.get(task_id)
        if task:
            task.update(fields)


def _remove_compare_task(task_id: str):
    # Remove a compare job from the job board after we no longer need it.
    # This cleans up temporary state only, not compare chat history.
    store = _get_compare_task_store()
    tasks = store["tasks"]
    lock = store["lock"]
    with lock:
        return tasks.pop(task_id, None)


def _request_compare_task_cancel(task_id: str):
    # This is what "Stop" means in Compare mode.
    # It does NOT clear old compare messages.
    # It only marks the current in-progress comparison as "please cancel".
    _set_compare_task_fields(task_id, cancel_requested=True)


def _start_compare_task(rag_pipeline, question: str, is_followup: bool) -> str:
    # Start a brand-new temporary compare job.
    # Think of this as creating a "draft comparison task" that runs in the background.
    # The returned task id is how the UI keeps track of that draft.
    task_id = uuid.uuid4().hex
    store = _get_compare_task_store()
    tasks = store["tasks"]
    lock = store["lock"]
    with lock:
        tasks[task_id] = {
            "status": "running",
            "cancel_requested": False,
            "question": question,
            "is_followup": is_followup,
            "result": None,
            "error": None,
        }

    def _cancel_check():
        # The backend keeps calling this while it works.
        # If it returns True, the backend knows the user clicked Stop.
        with lock:
            task = tasks.get(task_id)
            return bool(task and task.get("cancel_requested"))

    def _set_status(**fields):
        # Helper used by the worker to update the job board safely.
        # Example: switch status from "running" to "completed" or "cancelled".
        with lock:
            task = tasks.get(task_id)
            if task:
                task.update(fields)

    def _worker():
        # This is the background worker that does the real compare generation.
        # It runs outside the main UI flow so the page can stay responsive and show Stop.
        try:
            if rag_pipeline:
                result = rag_pipeline.answer_compare_definitions(
                    question,
                    concept=question,
                    cancel_check=_cancel_check,
                )
            else:
                result = {
                    "answer": (
                        "Mock mode: Backend not connected.\n"
                        "No grounded answer can be generated. "
                        "Please connect the backend (RAG pipeline) to enable cited answers."
                    ),
                    "evidence_dict": {},
                    "retrieved_docs": [],
                    "followup_questions": [],
                    "compare_sections": {},
                }

            if _cancel_check():
                _set_status(status="cancelled", result=None)
            else:
                _set_status(status="completed", result=result)
        except GenerationCancelled:
            _set_status(status="cancelled", result=None)
        except Exception as e:
            _set_status(status="error", error=str(e))

    threading.Thread(target=_worker, name=f"compare-task-{task_id[:8]}", daemon=True).start()
    return task_id


def _finalize_compare_task():
    # This is the bridge from "temporary compare job" to "visible compare chat".
    # If the job finished successfully, we append the result to compare history.
    # If the job was cancelled, we throw away only that temporary job.
    task_id = st.session_state.get("compare_task_id")
    if not task_id:
        return

    snapshot = _snapshot_compare_task(task_id)
    if not snapshot:
        st.session_state.pop("compare_task_id", None)
        return

    status = snapshot.get("status")
    if status == "completed":
        result = snapshot.get("result") or {}
        answer = result.get("answer", "No answer returned.")
        evidence_dict = result.get("evidence_dict", {})
        retrieved_docs = result.get("retrieved_docs", [])
        retrieved_docs_grouped = {}
        followup_questions = result.get("followup_questions", [])
        compare_sections = result.get("compare_sections", {})
        compare_row_refs = result.get("compare_row_refs", [])
        compare_debug = result.get("compare_debug", {})
        if isinstance(retrieved_docs, dict):
            policy_docs = retrieved_docs.get("policy", []) or []
            provider_docs = retrieved_docs.get("provider_manual", []) or []
            retrieved_docs_grouped = {
                "policy": policy_docs,
                "provider_manual": provider_docs,
            }
            retrieved_docs = policy_docs + provider_docs
        st.session_state["compare_history"].append({
            "role": "assistant",
            "content": answer,
            "evidence_dict": evidence_dict,
            "retrieved_docs": retrieved_docs,
            "retrieved_docs_grouped": retrieved_docs_grouped,
            "compare_sections": compare_sections,
            "compare_row_refs": compare_row_refs,
            "compare_debug": compare_debug,
            "followup_questions": followup_questions,
            "is_followup": bool(snapshot.get("is_followup")),
        })
        _remove_compare_task(task_id)
        st.session_state.pop("compare_task_id", None)
        st.rerun()

    if status == "cancelled":
        _remove_compare_task(task_id)
        st.session_state.pop("compare_task_id", None)
        st.session_state["compare_status_notice"] = (
            "Stopped the in-flight comparison. Earlier chat memory was preserved."
        )
        st.rerun()

    if status == "error":
        if st.session_state["compare_history"] and st.session_state["compare_history"][-1].get("role") == "user":
            st.session_state["compare_history"].pop()
        _remove_compare_task(task_id)
        st.session_state.pop("compare_task_id", None)
        st.session_state["compare_status_error"] = snapshot.get("error") or "Unknown error"
        st.rerun()


_finalize_compare_task()

# ============================================================
# ========== HELPERS =========================================
# ============================================================
def format_evidence_dict(evidence_dict):
    if not evidence_dict:
        return "No evidence returned."
    html_lines = []
    for _, ev in evidence_dict.items():
        doc_info = html.escape(str(ev.get("doc_info", "Unknown")))
        quote = html.escape(str(ev.get("quote", ""))).replace("\n", "<br>")
        publish_date = html.escape(str(ev.get("publish_date", "N/A")))
        url = html.escape(str(ev.get("url", "N/A")))
        html_lines.append(
            "<li>"
            f"<strong>{doc_info}</strong>, Published on {publish_date}: "
            f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\">{url}</a>"
            f"<div style=\"margin-top:0.35rem; padding-left:0.75rem; border-left:3px solid #E0E0E0; color:#333;\">{quote}</div>"
            "</li>"
        )
    return "\n".join(html_lines)

def format_retrieved_docs(retrieved_docs):
    if not retrieved_docs:
        return ""
    html_lines = []
    for doc in retrieved_docs:
        title = html.escape(str(doc.get("title", "")))
        doc_id = html.escape(str(doc.get("doc_id", "Unknown")))
        display_name = title if title else doc_id
        url = html.escape(str(doc.get("url", "N/A")))
        pages = html.escape(str(doc.get("pages", "N/A")))
        snippet = html.escape(str(doc.get("text", ""))[:300]).replace("\n", " ")
        html_lines.append(
            "<li>"
            f"<strong>{display_name}</strong> (pages {pages})<br>"
            f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\">{url}</a><br>"
            f"<span style=\"color:#666; font-size:0.9em;\">{snippet}...</span>"
            "</li>"
        )
    return "\n".join(html_lines)


def format_retrieved_docs_compare_table(retrieved_docs_grouped):
    """Render compare retrieved docs as a 2-column table: provider manual vs Medicaid Update."""
    policy_docs = retrieved_docs_grouped.get("policy", []) or []
    provider_docs = retrieved_docs_grouped.get("provider_manual", []) or []

    def _docs_to_ul(docs):
        if not docs:
            return "<em style='color:#666; font-size:0.9em;'>No sources retrieved.</em>"

        items = []
        for doc in docs:
            title = html.escape(str(doc.get("title", "")))
            doc_id = html.escape(str(doc.get("doc_id", "Unknown")))
            display_name = title if title else doc_id
            url = html.escape(str(doc.get("url", "N/A")))
            pages = html.escape(str(doc.get("pages", "N/A")))
            snippet = html.escape(str(doc.get("text", ""))[:280]).replace("\n", " ")
            items.append(
                "<li>"
                f"<strong>{display_name}</strong> (pages {pages})<br>"
                f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"word-break:break-all; overflow-wrap:anywhere;\">{url}</a><br>"
                f"<span style=\"color:#666; font-size:0.9em; word-break:break-word; overflow-wrap:anywhere;\">{snippet}...</span>"
                "</li>"
            )
        return f"<ul style='margin:0; padding-left:1.1rem; word-break:break-word; overflow-wrap:anywhere;'>{''.join(items)}</ul>"

    policy_html = _docs_to_ul(policy_docs)
    provider_html = _docs_to_ul(provider_docs)

    return f"""
    <div style="width:100%; overflow-x:auto;">
    <table style="width:100%; border-collapse:collapse; margin:0.6rem 0 0.2rem 0; table-layout:fixed;">
      <thead>
        <tr style="background:#E8F0FE; color:#333;">
          <th style="padding:8px 12px; border:1px solid #D0D0D0; width:50%; text-align:left;">Provider Manual Sources</th>
          <th style="padding:8px 12px; border:1px solid #D0D0D0; width:50%; text-align:left;">Medicaid Update Sources</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #D0D0D0; vertical-align:top; word-break:break-word; overflow-wrap:anywhere; color:#333;">{provider_html}</td>
          <td style="padding:8px 12px; border:1px solid #D0D0D0; vertical-align:top; word-break:break-word; overflow-wrap:anywhere; color:#333;">{policy_html}</td>
        </tr>
      </tbody>
    </table>
    </div>
    """


def format_compare_debug(debug_payload):
    if not debug_payload:
        return ""

    def _pretty(value):
        if value is None:
            return "null"
        if isinstance(value, str):
            return value
        return json.dumps(value, indent=2, ensure_ascii=False)

    sections = [
        ("Planner Raw", debug_payload.get("planner_raw")),
        ("Planner Parsed", debug_payload.get("planner_row_plan")),
        ("Normalized Row Plan", debug_payload.get("normalized_row_plan")),
        ("Writer Raw", debug_payload.get("writer_raw")),
        ("Writer Parsed", debug_payload.get("writer_sections")),
        ("Repair Flags Before", debug_payload.get("repair_flags_before")),
        ("Repair Raw", debug_payload.get("repair_raw")),
        ("Repair Parsed", debug_payload.get("repair_sections")),
        ("Repair Flags After", debug_payload.get("repair_flags_after")),
        ("Forced Sections", debug_payload.get("forced_sections")),
    ]

    blocks = []
    for label, value in sections:
        if value in (None, "", [], {}):
            continue
        blocks.append(
            f"<details style='margin-top:0.5rem;'>"
            f"<summary style='cursor:pointer; font-weight:600;'>{html.escape(label)}</summary>"
            f"<pre style='white-space:pre-wrap; word-break:break-word; background:#F7F9FC; border:1px solid #E1E7F0; border-radius:8px; padding:10px; margin-top:0.4rem; font-size:13px; line-height:1.45;'>{html.escape(_pretty(value))}</pre>"
            f"</details>"
        )

    if not blocks:
        return ""

    return (
        "<div style='margin-top:1rem; border-top:1px solid #E5E7EB; padding-top:0.75rem;'>"
        "<strong>Debug:</strong><br>"
        "<em style='color:#666; font-size:0.9em;'>Planner, normalizer, writer, repair, and fallback artifacts for this compare run.</em>"
        + "".join(blocks)
        + "</div>"
    )

_COMPARE_CSS = """
<style>
.chat-row { display: flex; align-items: flex-start; }
.chat-bubble {
    max-width: 95%; padding: 0.7rem 1rem; border-radius: 1rem;
    line-height: 1.6; word-wrap: break-word; box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}
.chat-bubble.assistant {
    background-color: #F4F4F4; border: 1px solid #E0E0E0; color: #000 !important;
    border-top-left-radius: 0.3rem; font-size: 15px;
}
.chat-bubble.assistant * {
    color: #000 !important;
}
.chat-bubble.assistant a {
    color: #1a6dd4 !important;
}
.avatar {
    width: 36px; height: 36px; border-radius: 50%;
    display: flex; align-items: center; justify-content: center;
    font-size: 18px; font-weight: bold; background-color: #E5E7EB; margin: 0 0.5rem;
}
.chat-bubble table { font-size: 14px; border-collapse: collapse; width: 100%; }
.chat-bubble table th { background-color: #E8F0FE; font-weight: 600; color: #333; }
.chat-bubble table td, .chat-bubble table th {
    padding: 8px 12px; border: 1px solid #D0D0D0; vertical-align: top; color: #333;
}
    .chat-bubble table td, .chat-bubble table th, .chat-bubble a, .chat-bubble li, .chat-bubble span {
        word-break: break-word;
        overflow-wrap: anywhere;
    }
    div[data-testid="stButton"] > button[kind="secondary"] {
        border-radius: 999px;
    }
    .generation-status {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 0.75rem;
        margin: 0.75rem 0 0.35rem 0;
        padding: 0.85rem 1rem;
        background: linear-gradient(135deg, #eef6ff 0%, #e2efff 100%);
        border: 1px solid #c9def8;
        border-radius: 14px;
    }
    .generation-status-text {
        color: #14559a;
        font-size: 15px;
    }
</style>
"""

def _wrap_compare_html(content: str) -> str:
    """Wrap compare HTML content with inline CSS for st.html() rendering."""
    return _COMPARE_CSS + content


def markdown_to_html(md_text: str) -> str:
    """Convert answer markdown to HTML with light normalization for list rendering."""
    if not md_text:
        return ""
    # Follow-up answers often come back as inline bullets, so normalize them first.
    normalized_md = re.sub(r"(?im)^answer\s*:?\s*", "", md_text, count=1).strip()
    # Force inline bullet patterns to become actual markdown lists.
    normalized_md = re.sub(r" \* ", "\n\n- ", normalized_md)
    normalized_md = re.sub(r"(?m)^\s*\*\s+", "- ", normalized_md)
    return markdown.markdown(normalized_md, extensions=["extra", "sane_lists"])


def _parse_effective_date(value):
    """Best-effort parse for document effective dates used in compare rendering."""
    if not value:
        return None
    if isinstance(value, date) and not isinstance(value, datetime):
        return value
    if isinstance(value, datetime):
        return value.date()
    raw = str(value).strip()
    if not raw or raw.upper() == "N/A":
        return None
    for parser in (
        lambda s: datetime.fromisoformat(s).date(),
        lambda s: datetime.strptime(s, "%Y-%m-%d").date(),
        lambda s: datetime.strptime(s, "%B %Y").date(),
        lambda s: datetime.strptime(s, "%b %Y").date(),
        lambda s: datetime.strptime(s, "%B %d, %Y").date(),
        lambda s: datetime.strptime(s, "%b %d, %Y").date(),
    ):
        try:
            return parser(raw)
        except ValueError:
            continue
    return None


def _effective_date_label(doc):
    return html.escape(str(doc.get("effective_date") or "N/A"))


def _doc_display_name(doc):
    title = str(doc.get("title", "")).strip()
    doc_id = str(doc.get("doc_id", "")).strip()
    return title or doc_id or "Unknown Document"


def _latest_doc(docs):
    dated_docs = []
    for doc in docs or []:
        parsed = _parse_effective_date(doc.get("effective_date"))
        if parsed is not None:
            dated_docs.append((parsed, doc))
    if not dated_docs:
        return None
    dated_docs.sort(key=lambda item: item[0], reverse=True)
    return dated_docs[0][1]


def _build_recency_summary(retrieved_docs_grouped):
    """Create a visible recency summary from retrieved policy/provider sources."""
    policy_latest = _latest_doc(retrieved_docs_grouped.get("policy", []))
    provider_latest = _latest_doc(retrieved_docs_grouped.get("provider_manual", []))

    if not policy_latest and not provider_latest:
        return (
            "Recency could not be determined from the retrieved sources because no usable "
            "effective dates were available."
        )

    parts = []
    if policy_latest:
        parts.append(
            f"Newest policy source: {_doc_display_name(policy_latest)} "
            f"(effective date: {_effective_date_label(policy_latest)})."
        )
    else:
        parts.append("Newest policy source: effective date unavailable from the retrieved policy sources.")

    if provider_latest:
        parts.append(
            f"Newest provider manual source: {_doc_display_name(provider_latest)} "
            f"(effective date: {_effective_date_label(provider_latest)})."
        )
    else:
        parts.append("Newest provider manual source: effective date unavailable from the retrieved provider manual sources.")

    policy_date = _parse_effective_date(policy_latest.get("effective_date")) if policy_latest else None
    provider_date = _parse_effective_date(provider_latest.get("effective_date")) if provider_latest else None

    if policy_date and provider_date:
        if policy_date > provider_date:
            parts.append(
                "Overall, the policy source is more up to date. The model will usually "
                "emphasize the more recent source, but the newest source may not always "
                "directly answer the question on its own."
            )
        elif provider_date > policy_date:
            parts.append(
                "Overall, the provider manual source is more up to date. The model will "
                "usually emphasize the more recent source, but the newest source may not "
                "always directly answer the question on its own."
            )
        else:
            parts.append("Overall, the newest policy and provider manual sources are tied on effective date.")
    else:
        parts.append("Overall recency across source types cannot be fully determined because one or both effective dates are unavailable.")

    return " ".join(parts)


def format_compare_tables(sections, retrieved_docs_grouped=None, compare_row_refs=None):
    """Render compare definitions result as headline + 2 HTML tables + caveats."""
    headline_raw = sections.get("headline_summary", "")
    aligned_pairs = sections.get("aligned_pairs", []) or []
    policy_def = sections.get("policy_definition", [])
    provider_def = sections.get("provider_manual_definition", [])
    similarities = sections.get("similarities", [])
    differences = sections.get("differences", [])
    caveats = sections.get("caveats")
    retrieved_docs_grouped = retrieved_docs_grouped or {}
    compare_row_refs = compare_row_refs or []

    citation_to_num = {}
    citation_order = []
    known_docs = {}

    for docs in retrieved_docs_grouped.values():
        for doc in docs or []:
            display_name = _doc_display_name(doc)
            known_docs[display_name] = doc
            doc_id = str(doc.get("doc_id", "")).strip()
            if doc_id:
                known_docs[doc_id] = doc

    def _match_doc_for_citation(cite: str):
        cleaned = str(cite or "").strip()
        if not cleaned:
            return None
        best_match = None
        best_len = -1
        for candidate, doc in known_docs.items():
            candidate = str(candidate or "").strip()
            if not candidate:
                continue
            if cleaned == candidate or cleaned.startswith(candidate + ":") or cleaned.startswith(candidate + " —") or cleaned.startswith(candidate + " â€”"):
                if len(candidate) > best_len:
                    best_match = doc
                    best_len = len(candidate)
        return best_match

    def _date_from_citation_text(cite: str) -> str:
        cleaned = str(cite or "").strip()
        if not cleaned:
            return "N/A"
        for sep in (" — ", " â€” "):
            if sep in cleaned:
                tail = cleaned.rsplit(sep, 1)[1].strip()
                if _parse_effective_date(tail):
                    return html.escape(tail)
        return "N/A"

    def _strip_trailing_date_from_citation(cite: str) -> str:
        cleaned = str(cite or "").strip()
        if not cleaned:
            return ""
        for sep in (" â€” ", " Ã¢â‚¬â€ "):
            if sep in cleaned:
                head, tail = cleaned.rsplit(sep, 1)
                if _parse_effective_date(tail.strip()):
                    return head.strip()
        return cleaned

    def _humanize_writer_citation(cite: str):
        cleaned = _strip_trailing_date_from_citation(cite)
        matched_doc = _match_doc_for_citation(cleaned) or _match_doc_for_citation(str(cite or "").strip())
        if matched_doc:
            return {
                "display_name": _doc_display_name(matched_doc),
                "pages": matched_doc.get("pages", "N/A"),
                "effective_date": _effective_date_label(matched_doc),
            }

        display_names = []
        for piece in re.split(r"\s*,\s*", cleaned):
            token = str(piece or "").strip()
            if not token:
                continue
            token = token.split("::", 1)[0].strip()
            doc = _match_doc_for_citation(token)
            if doc:
                label = _doc_display_name(doc)
            else:
                label = re.sub(r"^.*[\\/]", "", token)
                label = re.sub(r"\.pdf$", "", label, flags=re.IGNORECASE)
                label = label.replace("_", " ").strip(" -:")
            if label and label not in display_names:
                display_names.append(label)

        return {
            "display_name": ", ".join(display_names) if display_names else "Retrieved document snippet",
            "pages": "N/A",
            "effective_date": _date_from_citation_text(cite),
        }

    def _split_writer_citation_pieces(cite: str) -> list:
        cleaned = _strip_trailing_date_from_citation(cite)
        pieces = []
        seen = set()
        for piece in re.split(r"\s*,\s*", cleaned):
            token = str(piece or "").strip()
            if not token:
                continue
            if token not in seen:
                seen.add(token)
                pieces.append(token)
        return pieces or ([str(cleaned).strip()] if str(cleaned).strip() else [])

    def _register_deterministic_ref(ref_item: dict) -> int:
        chunk_id = str(ref_item.get("chunk_id", "")).strip()
        doc_id = str(ref_item.get("doc_id", "")).strip()
        key = f"chunk::{chunk_id}" if chunk_id else f"doc::{doc_id}"
        if not key or key.endswith("::"):
            return 0
        if key not in citation_to_num:
            citation_to_num[key] = len(citation_order) + 1
            citation_order.append(
                {
                    "kind": "deterministic",
                    "key": key,
                    "chunk_id": chunk_id,
                    "doc_id": doc_id,
                    "title": str(ref_item.get("title", "")).strip() or doc_id or "Unknown Document",
                    "pages": ref_item.get("pages", "N/A"),
                    "effective_date": ref_item.get("effective_date", "N/A"),
                }
            )
        return citation_to_num[key]

    for row_ref in compare_row_refs:
        for side in ("provider_manual", "policy_update"):
            for ref_item in row_ref.get(side, []) or []:
                _register_deterministic_ref(ref_item)

    def _register_writer_citation(cite: str) -> list:
        numbers = []
        for piece in _split_writer_citation_pieces(cite):
            matched_doc = _match_doc_for_citation(piece)
            if matched_doc:
                doc_id = str(matched_doc.get("doc_id", "")).strip()
                display_name = _doc_display_name(matched_doc)
                key = f"writer-doc::{doc_id or display_name}"
                if key not in citation_to_num:
                    citation_to_num[key] = len(citation_order) + 1
                    citation_order.append(
                        {
                            "kind": "writer_resolved",
                            "key": key,
                            "display_name": display_name,
                            "pages": matched_doc.get("pages", "N/A"),
                            "effective_date": _effective_date_label(matched_doc),
                        }
                    )
                numbers.append(citation_to_num[key])
                continue

            key = f"writer::{piece}"
            if key not in citation_to_num:
                citation_to_num[key] = len(citation_order) + 1
                citation_order.append({"kind": "writer", "cite": piece})
            numbers.append(citation_to_num[key])
        return numbers

    def _normalize_text_with_inline_numbers(text: str) -> str:
        # Replace raw inline citation strings with stable numeric references like [1].
        if text is None:
            return ""
        raw = str(text)

        def _is_valid_citation_text(cite: str) -> bool:
            cleaned = re.sub(r"\s+", " ", (cite or "")).strip()
            if not cleaned:
                return False
            if cleaned in {"...", "..", "."}:
                return False
            if re.fullmatch(r"[\.\,\;\:\-\u2013\u2014\s]+", cleaned):
                return False
            if len(re.sub(r"[\W_]+", "", cleaned)) < 3:
                return False
            return True
        
        def _replace_citation(match):
            cite = match.group(1).strip()
            # Keep already-numbered citations as-is to avoid stripping them.
            if re.fullmatch(r"\d{1,3}", cite):
                return f" [{cite}]"
            if not _is_valid_citation_text(cite):
                # Do not drop unknown citation tokens; dropping can leave broken tails like "or ."
                return match.group(0)
            nums = _register_writer_citation(cite)
            return f" {' '.join(f'[{n}]' for n in nums)}" if nums else match.group(0)

        def _looks_like_writer_citation(cite: str) -> bool:
            cleaned = re.sub(r"\s+", " ", (cite or "")).strip()
            if not cleaned:
                return False
            return (
                "::" in cleaned
                or ".pdf" in cleaned.lower()
                or re.search(r"\bmu_[A-Za-z0-9_]+\b", cleaned) is not None
                or re.search(r"\bVolume\s+\d+\b", cleaned, flags=re.IGNORECASE) is not None
            )

        def _replace_parenthetical_citation(match):
            cite = match.group(1).strip()
            if not _looks_like_writer_citation(cite) or not _is_valid_citation_text(cite):
                return match.group(0)
            nums = _register_writer_citation(cite)
            return f" {' '.join(f'[{n}]' for n in nums)}" if nums else match.group(0)

        normalized = re.sub(r"\[([^\[\]]+)\]", _replace_citation, raw)
        normalized = re.sub(r"\(([^()]*?(?:::|\.pdf|mu_[A-Za-z0-9_]+)[^()]*)\)", _replace_parenthetical_citation, normalized)
        normalized = re.sub(r"\s{2,}", " ", normalized).strip()
        normalized = re.sub(r"\s+([.,;:!?])", r"\1", normalized)
        return html.escape(normalized)

    def _normalize_first_table_text(text: str, ref_items: list) -> str:
        cleaned = re.sub(r"\[[^\[\]]+\]", "", str(text or ""))
        cleaned = re.sub(r"\s{2,}", " ", cleaned).strip()
        cleaned = re.sub(r"\s+([.,;:!?])", r"\1", cleaned)
        suffix_numbers = []
        for ref_item in ref_items or []:
            n = _register_deterministic_ref(ref_item)
            if n:
                suffix_numbers.append(f"[{n}]")
        suffix = f" {' '.join(suffix_numbers)}" if suffix_numbers else ""
        return html.escape(cleaned) + suffix

    def _normalize_bullet_items(value, empty_text: str) -> str:
        if isinstance(value, str):
            items = [value] if value.strip() else []
        elif isinstance(value, list):
            items = [str(item).strip() for item in value if str(item).strip()]
        else:
            items = []
        if not items:
            items = [empty_text]
        return "".join(
            f"<li>{_normalize_text_with_inline_numbers(item)}</li>" for item in items
        )

    headline = _normalize_text_with_inline_numbers(headline_raw)
    # Final headline cleanup to avoid dangling connector tails after citation normalization.
    headline = re.sub(r"\s+([.,;:!?])", r"\1", headline).strip()
    headline = re.sub(
        r"\b(?:and|or|for|with|including)\s*(?:\[\d+\])?\s*([.,;:!?])\s*$",
        r"\1",
        headline,
        flags=re.IGNORECASE,
    )
    headline = re.sub(
        r"\b(?:and|or|for|with|including)\s*(?:\[\d+\])?\s*$",
        "",
        headline,
        flags=re.IGNORECASE,
    ).strip()

    if aligned_pairs:
        row_html = []
        for _, pair in enumerate(aligned_pairs, start=1):
            provider_text = pair.get("provider_manual", "") or "No grounded provider manual evidence was available for this point."
            policy_text = pair.get("policy_update", "") or "No closely matching policy evidence was available for this provider-manual point."
            row_ref = compare_row_refs[_ - 1] if (_ - 1) < len(compare_row_refs) else {}
            row_html.append(
                "<tr>"
                f"<td style=\"padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;\">"
                f"<ul style=\"margin:0; padding-left:1.2rem;\"><li>{_normalize_first_table_text(provider_text, row_ref.get('provider_manual', []))}</li></ul>"
                "</td>"
                f"<td style=\"padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;\">"
                f"<ul style=\"margin:0; padding-left:1.2rem;\"><li>{_normalize_first_table_text(policy_text, row_ref.get('policy_update', []))}</li></ul>"
                "</td>"
                "</tr>"
            )
        table1_body = "".join(row_html)
    else:
        policy_def_html = _normalize_bullet_items(
            policy_def,
            "No grounded policy evidence was available for this point.",
        )
        provider_def_html = _normalize_bullet_items(
            provider_def,
            "No grounded provider manual evidence was available for this point.",
        )
        table1_body = (
            "<tr>"
            f"<td style=\"padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;\"><ul style=\"margin:0; padding-left:1.2rem;\">{provider_def_html}</ul></td>"
            f"<td style=\"padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;\"><ul style=\"margin:0; padding-left:1.2rem;\">{policy_def_html}</ul></td>"
            "</tr>"
        )
    sim_items_html = "".join(
        f"<li>{_normalize_text_with_inline_numbers(s)}</li>" for s in similarities
    ) or "<li>None identified</li>"
    diff_items_html = "".join(
        f"<li>{_normalize_text_with_inline_numbers(d)}</li>" for d in differences
    ) or "<li>None identified</li>"

    table1 = f"""
    <table style="width:100%; border-collapse:collapse; margin:0.8rem 0;">
      <thead>
        <tr style="background:#E8F0FE; color:#333;">
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Provider Manual Definition</th>
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Medicaid Update Definition</th>
        </tr>
      </thead>
      <tbody>
        {table1_body}
      </tbody>
    </table>
    """

    table2 = f"""
    <table style="width:100%; border-collapse:collapse; margin:0.8rem 0;">
      <thead>
        <tr style="background:#E8F0FE; color:#333;">
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Similarities</th>
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Differences</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;"><ul style="margin:0; padding-left:1.2rem;">{sim_items_html}</ul></td>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top; color:#333;"><ul style="margin:0; padding-left:1.2rem;">{diff_items_html}</ul></td>
        </tr>
      </tbody>
    </table>
    """

    caveats_html = ""
    if caveats:
        caveats_html = f'<p style="color:#856404; background:#FFF3CD; padding:8px 12px; border-radius:4px; margin-top:0.5rem;"><b>Caveats:</b> {html.escape(str(caveats))}</p>'

    references_html = ""
    if citation_order:
        ref_items = []
        for i, entry in enumerate(citation_order, 1):
            if isinstance(entry, dict) and entry.get("kind") == "deterministic":
                display_name = html.escape(str(entry.get("title") or "Unknown Document"))
                pages = html.escape(str(entry.get("pages", "N/A")))
                effective_label = html.escape(str(entry.get("effective_date", "N/A")))
                ref_items.append(
                    f"<li>[{i}] {display_name} (pages {pages})"
                    f"<div style='color:#666; font-size:0.9em;'>Effective date: {effective_label}</div></li>"
                )
                continue
            if isinstance(entry, dict) and entry.get("kind") == "writer_resolved":
                display_name = html.escape(str(entry.get("display_name") or "Retrieved document snippet"))
                pages = str(entry.get("pages", "N/A"))
                effective_label = html.escape(str(entry.get("effective_date") or "N/A"))
                if pages and pages != "N/A":
                    ref_items.append(
                        f"<li>[{i}] {display_name} (pages {html.escape(pages)})"
                        f"<div style='color:#666; font-size:0.9em;'>Effective date: {effective_label}</div></li>"
                    )
                else:
                    ref_items.append(
                        f"<li>[{i}] {display_name}"
                        f"<div style='color:#666; font-size:0.9em;'>Effective date: {effective_label}</div></li>"
                    )
                continue
            cite = entry.get("cite") if isinstance(entry, dict) else str(entry)
            humanized = _humanize_writer_citation(cite)
            display_name = html.escape(str(humanized.get("display_name") or "Retrieved document snippet"))
            effective_label = html.escape(str(humanized.get("effective_date") or "N/A"))
            pages = str(humanized.get("pages", "N/A"))
            if pages and pages != "N/A":
                ref_items.append(
                    f"<li>[{i}] {display_name} (pages {html.escape(pages)})"
                    f"<div style='color:#666; font-size:0.9em;'>Effective date: {effective_label}</div></li>"
                )
            else:
                ref_items.append(
                    f"<li>[{i}] {display_name}"
                    f"<div style='color:#666; font-size:0.9em;'>Effective date: {effective_label}</div></li>"
                )
        references_html = (
            "<b>References:</b>"
            f"<ol style='margin-top:0.5rem; padding-left:1.4rem;'>{''.join(ref_items)}</ol>"
        )

    recency_summary = html.escape(_build_recency_summary(retrieved_docs_grouped))
    recency_html = (
        "<div style='margin-bottom:0.8rem; padding:10px 12px; background:#EEF6FF; "
        "color:#333; border:1px solid #CFE3FF; border-radius:8px;'>"
        "<b>Most Up-To-Date Source Signal:</b> "
        f"{recency_summary}"
        "</div>"
    )

    return f"""
    {recency_html}
    <p style="font-weight:600; margin-bottom:0.5rem;">{headline}</p>
    <b>Definitions:</b>
    {table1}
    <b>Comparison:</b>
    {table2}
    {references_html}
    {caveats_html}
    """


# ============================================================
# ========== SESSION STATE ===================================
# ============================================================
if "compare_history" not in st.session_state:
    st.session_state["compare_history"] = []

# ============================================================
# ========== DISPLAY HISTORY ================================
# ============================================================
st.markdown(
    """
    <style>
    .chat-container { display: flex; flex-direction: column; gap: 1rem; margin-bottom: 1rem; font-size: 15px; }
    .chat-row { display: flex; align-items: flex-start; }
    .chat-row.user { justify-content: flex-end; }
    .chat-bubble {
        max-width: 70%;
        padding: 0.7rem 1rem;
        border-radius: 1rem;
        line-height: 1.6;
        word-wrap: break-word;
        box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }
    .chat-bubble.assistant {
        background-color: #F4F4F4;
        border: 1px solid #E0E0E0;
        color: #000 !important;
        border-top-left-radius: 0.3rem;
    }
    .chat-bubble.assistant * {
        color: #000 !important;
    }
    .chat-bubble.assistant a {
        color: #1a6dd4 !important;
    }
    .chat-bubble.user {
        background-color: #DCF2FF;
        border: 1px solid #CDE9FF;
        color: #000 !important;
        border-top-right-radius: 0.3rem;
    }
    .chat-bubble.user * {
        color: #000 !important;
    }
    .avatar {
        width: 36px; height: 36px;
        border-radius: 50%;
        display: flex; align-items: center; justify-content: center;
        font-size: 18px; font-weight: bold;
        background-color: #E5E7EB;
        margin: 0 0.5rem;
    }
    .avatar.user { background-color: #CDE9FF; }
    input, button, label, div[data-testid="stMarkdownContainer"] {
        font-size: 15px !important;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown('<div class="chat-container">', unsafe_allow_html=True)
for msg in st.session_state["compare_history"]:
    role = msg["role"]
    text = msg["content"]

    if role == "assistant":
        evidence_dict = msg.get("evidence_dict", {})
        formatted_evidence = format_evidence_dict(evidence_dict)
        retrieved_docs = msg.get("retrieved_docs", [])
        retrieved_docs_grouped = msg.get("retrieved_docs_grouped", {})
        formatted_sources = format_retrieved_docs(retrieved_docs) if retrieved_docs else ""
        compare_sections = msg.get("compare_sections", {})
        compare_row_refs = msg.get("compare_row_refs", [])
        compare_debug = msg.get("compare_debug", {})
        is_followup = bool(msg.get("is_followup", False))

        answer_body = text
        answer_body_is_html = False
        # Render as custom HTML tables whenever valid compare_sections are available.
        if compare_sections and not compare_sections.get("_parse_failed"):
            answer_body = format_compare_tables(
                compare_sections,
                retrieved_docs_grouped=retrieved_docs_grouped,
                compare_row_refs=compare_row_refs,
            )
            answer_body_is_html = True

        answer_body_html = answer_body if answer_body_is_html else markdown_to_html(answer_body)

        has_grouped_sources = bool(retrieved_docs_grouped) and (
            bool(retrieved_docs_grouped.get("policy")) or bool(retrieved_docs_grouped.get("provider_manual"))
        )
        has_sources = bool(retrieved_docs) or has_grouped_sources

        if is_followup and not answer_body_is_html:
            # Fallback: follow-ups without valid compare_sections render as plain markdown.
            st.markdown(
                """
<div class="chat-row assistant">
<div class="avatar assistant">&#x1F914;</div>
<div class="chat-bubble assistant">
                """,
                unsafe_allow_html=True,
            )
            st.markdown("**Answer:**")
            display_text = text.strip()
            display_text = re.sub(r"^answer\s*:?\s*", "", display_text, count=1, flags=re.IGNORECASE).strip()
            display_text = re.sub(r" \* ", "\n- ", display_text)
            display_text = re.sub(r"(?m)^\s*\*\s+", "- ", display_text)
            display_text = re.sub(r" \- (?=[A-Za-z0-9\"'])", "\n- ", display_text)
            st.markdown(display_text)
            if evidence_dict:
                st.markdown("")
                st.markdown("**Evidence:**")
                st.markdown("_Direct quotes from official documents that support the answer above._")
                st.markdown(
                    f"<ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_evidence}</ul>",
                    unsafe_allow_html=True,
                )
            if has_sources:
                st.markdown("")
                st.markdown("**Retrieved Sources:**")
                st.markdown("_Document snippets that were retrieved and analyzed to answer your question._")
                st.markdown(
                    f"<ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_sources}</ul>",
                    unsafe_allow_html=True,
                )
            st.markdown("</div></div>", unsafe_allow_html=True)
        else:
            if has_sources:
                if has_grouped_sources:
                    # Initial compare results keep policy/provider sources separated side by side.
                    retrieved_sources_html = (
                        "<strong>&#x1F4DA; Retrieved Sources:</strong><br>"
                        "<em style=\"color: #666; font-size: 0.9em;\">Policy sources are on the left; provider manual sources are on the right.</em>"
                        + format_retrieved_docs_compare_table(retrieved_docs_grouped)
                    )
                else:
                    retrieved_sources_html = f"""
<strong>&#x1F4DA; Retrieved Sources:</strong><br>
<em style="color: #666; font-size: 0.9em;">Document snippets that were retrieved and analyzed to answer your question.</em>
<ul style="margin-top: 0.5rem; padding-left: 1.5rem;">
{formatted_sources}
</ul>
"""
                display_content = f"""
<div class="chat-row assistant">
<div class="avatar assistant">&#x1F914;</div>
<div class="chat-bubble assistant">
{answer_body_html}
{"<br><br><b>Evidence:</b><br><em style='color: #666; font-size: 0.9em;'>Direct quotes from official documents that support the answer above.</em><ul style='margin-top:0.5rem; padding-left:1.5rem;'>" + formatted_evidence + "</ul>" if evidence_dict else ""}
{retrieved_sources_html}
 {format_compare_debug(compare_debug) if compare_debug else ""}
</div>
</div>
"""
            else:
                display_content = f"""
<div class="chat-row assistant">
<div class="avatar assistant">&#x1F914;</div>
<div class="chat-bubble assistant">
{answer_body_html}
{"" if not evidence_dict else f"<br><br><b>Evidence:</b><br><em style='color: #666; font-size: 0.9em;'>Direct quotes from official documents that support the answer above.</em><ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_evidence}</ul>"}
 {format_compare_debug(compare_debug) if compare_debug else ""}
</div>
</div>
"""
            if compare_sections and not compare_sections.get("_parse_failed"):
                st.html(_wrap_compare_html(display_content))
            else:
                st.markdown(display_content, unsafe_allow_html=True)
    else:
        safe_text = html.escape(text)
        st.markdown(
            f"""<div class="chat-row user">
                <div class="chat-bubble user">{safe_text}</div>
                <div class="avatar user">&#x1F464;</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
st.markdown('</div>', unsafe_allow_html=True)

# ============================================================
# ========== FOLLOW-UP QUESTION BUTTONS ======================
# ============================================================
active_compare_task = _snapshot_compare_task(st.session_state.get("compare_task_id", ""))
is_generating_compare = bool(active_compare_task)


@st.fragment(run_every="1s")
def render_compare_generation_controls():
    # Show the "currently comparing" UI for the active job.
    # This is where the user sees the banner and the Stop button.
    _finalize_compare_task()
    task_id = st.session_state.get("compare_task_id")
    if not task_id:
        return

    snapshot = _snapshot_compare_task(task_id)
    if not snapshot:
        st.session_state.pop("compare_task_id", None)
        return

    if snapshot.get("status") == "running":
        col1, col2, col3 = st.columns([7.2, 0.8, 1.2], vertical_alignment="center")
        with col1:
            st.markdown(
                """
                <div class="generation-status">
                    <div class="generation-status-text">
                        Comparing definitions. You can stop this turn without clearing earlier chat memory.
                    </div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with col2:
            st.markdown("&nbsp;", unsafe_allow_html=True)
        with col3:
            if st.button("Stop", key=f"stop_compare_generation_{task_id}", type="secondary", use_container_width=True):
                _request_compare_task_cancel(task_id)
                st.rerun()
        if snapshot.get("cancel_requested"):
            st.caption("Stopping the current comparison and preserving earlier chat memory.")


if is_generating_compare:
    render_compare_generation_controls()

if (not is_generating_compare) and st.session_state["compare_history"]:
    last_msg = st.session_state["compare_history"][-1]
    if last_msg.get("role") == "assistant":
        has_suggestions = bool(last_msg.get("followup_questions"))
        if has_suggestions:
            st.markdown("**Suggested follow-up questions:**")
            cols = st.columns(len(last_msg["followup_questions"]))
            for i, (col, q) in enumerate(zip(cols, last_msg["followup_questions"])):
                with col:
                    if st.button(q, key=f"compare_followup_{i}"):
                        st.session_state["compare_history"].append({"role": "user", "content": q})
                        rag_pipeline = get_rag_pipeline_lazy()
                        st.session_state["compare_task_id"] = _start_compare_task(
                            rag_pipeline=rag_pipeline,
                            question=q,
                            is_followup=True,
                        )
                        st.rerun()


# ============================================================
# ========== INPUT AREA ======================================
# ============================================================
submitted = False
followup_submitted = False
cleared = False

if not is_generating_compare:
    with st.container():
        st.markdown('<div class="input-box">', unsafe_allow_html=True)

        with st.form("compare_form", clear_on_submit=True):
            user_query = st.text_input(
                "🔎 **Compare a Concept:**",
                placeholder="e.g. How should providers bill managed care organizations for pharmacy claims today?",
            )

            has_assistant_response = any(
                msg.get("role") == "assistant" for msg in st.session_state["compare_history"]
            )

            if has_assistant_response:
                col1, col2 = st.columns([1, 1])
                with col1:
                    followup_submitted = st.form_submit_button("↪️ Ask Follow-Up", use_container_width=True)
                with col2:
                    cleared = st.form_submit_button("🧹 Clear", use_container_width=True)
            else:
                submitted = st.form_submit_button("🔍 Compare", use_container_width=True)

        st.markdown('</div>', unsafe_allow_html=True)

# ============================================================
# ========== CLEAR / SUBMIT ==================================
# ============================================================
if cleared:
    st.session_state["compare_history"] = []
    rag_pipeline = st.session_state.get("compare_rag_pipeline")
    if rag_pipeline:
        try:
            rag_pipeline.chat_history.clear()
        except Exception as e:
            st.error(f"Error clearing chat history: {e}")
    st.rerun()

# Submit logic ? phase 1
if submitted:
    if not user_query.strip():
        st.warning("Please enter a concept before comparing.")
    else:
        # A brand-new compare query resets the conversation to a fresh compare session.
        st.session_state["compare_history"] = [{"role": "user", "content": user_query}]
        rag_pipeline = st.session_state.get("compare_rag_pipeline")
        if rag_pipeline:
            try:
                rag_pipeline.chat_history.clear()
            except Exception:
                pass
        rag_pipeline = get_rag_pipeline_lazy()
        st.session_state["compare_task_id"] = _start_compare_task(
            rag_pipeline=rag_pipeline,
            question=user_query,
            is_followup=False,
        )
        st.rerun()

if followup_submitted:
    if not user_query.strip():
        st.warning("Please enter a follow-up question before submitting.")
    else:
        st.session_state["compare_history"].append({"role": "user", "content": user_query})
        rag_pipeline = get_rag_pipeline_lazy()
        st.session_state["compare_task_id"] = _start_compare_task(
            rag_pipeline=rag_pipeline,
            question=user_query,
            is_followup=True,
        )
        st.rerun()

# Submit logic — phase 2
