import streamlit as st
from PIL import Image
from pathlib import Path
import sys
import traceback
import html
import markdown

# ============================================================
# ========== PATH SETUP ======================================
# ============================================================
st.set_page_config(page_title="Compare Definitions - NYS Policies Assistant", layout="wide")

ROOT = Path(__file__).resolve().parents[2]  # project root
SRC_DIR = ROOT / "src"
sys.path.append(str(SRC_DIR))  # allow import from src/

# ============================================================
# ========== IMPORT PIPELINE MODULES =========================
# ============================================================
try:
    from healthcare_rag_llm.llm.llm_client import LLMClient
    from healthcare_rag_llm.llm.response_generator import ResponseGenerator
    from healthcare_rag_llm.filters.load_metadata import build_filter_extractor
    HAS_BACKEND = True
except Exception as e:
    HAS_BACKEND = False
    st.exception(e)
    st.code(traceback.format_exc())
    st.warning(f"⚠️ Backend import failed: {e}. Mock mode enabled.")

# ============================================================
# ========== HEADER ==========================================
# ============================================================
ROOT_DIR = Path(__file__).parent.parent
ASSETS_DIR = ROOT_DIR / "assets"
nys_logo_path = ASSETS_DIR / "nys_logo.png"

col1, col2 = st.columns([5, 1])
with col1:
    st.title("Compare Definitions")
    st.caption("Side-by-side comparison of definitions across policy and provider manual documents.")
with col2:
    if nys_logo_path.exists():
        nys_logo = Image.open(nys_logo_path)
        st.image(nys_logo, width=200)
    else:
        st.text("NYS Logo Missing")

# ============================================================
# ========== DISCLAIMER ======================================
# ============================================================
with st.expander("📜 Disclaimer", expanded=True):
    st.markdown("""
This assistant is part of the **Columbia University x KPMG Capstone Project**:
*Intelligent Document Analysis for Healthcare Programs Using LLMs and RAG.*

The responses are generated by an AI model referencing official
New York State Medicaid documents and related authorities.
They do not constitute legal advice.
""")

with st.expander("ℹ️ About and How It Works", expanded=True):
    st.markdown("""
**Purpose (Comparison)**  
Compare how a concept is defined in policy vs provider manuals.

**How it works**  
We retrieve both sources and generate a cited side-by-side comparison.

**Tips**  
Use a concise concept (e.g., "medical necessity") and add qualifiers if needed.
""")

# ============================================================
# ========== INITIALIZE RAG PIPELINE =========================
# ============================================================
@st.cache_resource
def load_rag_pipeline():
    if not HAS_BACKEND:
        return None
    from healthcare_rag_llm.utils.api_config import APIConfigManager
    api_config_manager = APIConfigManager()
    api_config_default = api_config_manager.get_default_config()
    llm_client = LLMClient(
        api_key=api_config_default.api_key,
        model="gemini-2.5-flash",
        provider=api_config_default.provider,
        base_url=api_config_default.base_url
    )
    filter_extractor = build_filter_extractor()
    return ResponseGenerator(llm_client, filter_extractor=filter_extractor)

def get_rag_pipeline_lazy():
    if "compare_rag_pipeline" not in st.session_state:
        st.session_state["compare_rag_pipeline"] = load_rag_pipeline()
    return st.session_state["compare_rag_pipeline"]

# ============================================================
# ========== HELPERS =========================================
# ============================================================
def format_evidence_dict(evidence_dict):
    if not evidence_dict:
        return "No evidence returned."
    html_lines = []
    for _, ev in evidence_dict.items():
        doc_info = html.escape(str(ev.get("doc_info", "Unknown")))
        quote = html.escape(str(ev.get("quote", ""))).replace("\n", "<br>")
        publish_date = html.escape(str(ev.get("publish_date", "N/A")))
        url = html.escape(str(ev.get("url", "N/A")))
        html_lines.append(
            "<li>"
            f"<strong>{doc_info}</strong>, Published on {publish_date}: "
            f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\">{url}</a>"
            f"<div style=\"margin-top:0.35rem; padding-left:0.75rem; border-left:3px solid #E0E0E0; color:#333;\">{quote}</div>"
            "</li>"
        )
    return "\n".join(html_lines)

def format_retrieved_docs(retrieved_docs):
    if not retrieved_docs:
        return ""
    html_lines = []
    for doc in retrieved_docs:
        title = html.escape(str(doc.get("title", "")))
        doc_id = html.escape(str(doc.get("doc_id", "Unknown")))
        display_name = title if title else doc_id
        url = html.escape(str(doc.get("url", "N/A")))
        pages = html.escape(str(doc.get("pages", "N/A")))
        snippet = html.escape(str(doc.get("text", ""))[:300]).replace("\n", " ")
        html_lines.append(
            "<li>"
            f"<strong>{display_name}</strong> (pages {pages})<br>"
            f"<a href=\"{url}\" target=\"_blank\" rel=\"noopener noreferrer\">{url}</a><br>"
            f"<span style=\"color:#666; font-size:0.9em;\">{snippet}...</span>"
            "</li>"
        )
    return "\n".join(html_lines)

_COMPARE_CSS = """
<style>
.chat-row { display: flex; align-items: flex-start; }
.chat-bubble {
    max-width: 95%; padding: 0.7rem 1rem; border-radius: 1rem;
    line-height: 1.6; word-wrap: break-word; box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}
.chat-bubble.assistant {
    background-color: #F4F4F4; border: 1px solid #E0E0E0; color: #000;
    border-top-left-radius: 0.3rem; font-size: 15px;
}
.avatar {
    width: 36px; height: 36px; border-radius: 50%;
    display: flex; align-items: center; justify-content: center;
    font-size: 18px; font-weight: bold; background-color: #E5E7EB; margin: 0 0.5rem;
}
.chat-bubble table { font-size: 14px; border-collapse: collapse; width: 100%; }
.chat-bubble table th { background-color: #E8F0FE; font-weight: 600; }
.chat-bubble table td, .chat-bubble table th {
    padding: 8px 12px; border: 1px solid #D0D0D0; vertical-align: top;
}
</style>
"""

def _wrap_compare_html(content: str) -> str:
    """Wrap compare HTML content with inline CSS for st.html() rendering."""
    return _COMPARE_CSS + content


def markdown_to_html(md_text: str) -> str:
    """Convert markdown to HTML while escaping raw HTML for safety."""
    if not md_text:
        return ""
    safe_md = html.escape(md_text)
    return markdown.markdown(safe_md, extensions=["extra", "sane_lists"])


def format_compare_tables(sections):
    """Render compare definitions result as headline + 2 HTML tables + caveats."""
    headline = html.escape(sections.get("headline_summary", ""))
    policy_def = sections.get("policy_definition", "N/A")
    provider_def = sections.get("provider_manual_definition", "N/A")
    similarities = sections.get("similarities", [])
    differences = sections.get("differences", [])
    caveats = sections.get("caveats")

    table1 = f"""
    <table style="width:100%; border-collapse:collapse; margin:0.8rem 0;">
      <thead>
        <tr style="background:#E8F0FE;">
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Policy Definition</th>
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Provider Manual Definition</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top;">{policy_def}</td>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top;">{provider_def}</td>
        </tr>
      </tbody>
    </table>
    """

    sim_items = "".join(f"<li>{s}</li>" for s in similarities) or "<li>None identified</li>"
    diff_items = "".join(f"<li>{d}</li>" for d in differences) or "<li>None identified</li>"

    table2 = f"""
    <table style="width:100%; border-collapse:collapse; margin:0.8rem 0;">
      <thead>
        <tr style="background:#E8F0FE;">
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Similarities</th>
          <th style="padding:8px 12px; border:1px solid #ccc; width:50%; text-align:left;">Differences</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top;"><ul style="margin:0; padding-left:1.2rem;">{sim_items}</ul></td>
          <td style="padding:8px 12px; border:1px solid #ccc; vertical-align:top;"><ul style="margin:0; padding-left:1.2rem;">{diff_items}</ul></td>
        </tr>
      </tbody>
    </table>
    """

    caveats_html = ""
    if caveats:
        caveats_html = f'<p style="color:#856404; background:#FFF3CD; padding:8px 12px; border-radius:4px; margin-top:0.5rem;"><b>Caveats:</b> {html.escape(str(caveats))}</p>'

    return f"""
    <p style="font-weight:600; margin-bottom:0.5rem;">{headline}</p>
    <b>Definitions:</b>
    {table1}
    <b>Comparison:</b>
    {table2}
    {caveats_html}
    """


# ============================================================
# ========== SESSION STATE ===================================
# ============================================================
if "compare_history" not in st.session_state:
    st.session_state["compare_history"] = []

# ============================================================
# ========== DISPLAY HISTORY ================================
# ============================================================
st.markdown(
    """
    <style>
    .chat-container { display: flex; flex-direction: column; gap: 1rem; margin-bottom: 1rem; font-size: 15px; }
    .chat-row { display: flex; align-items: flex-start; }
    .chat-row.user { justify-content: flex-end; }
    .chat-bubble {
        max-width: 70%;
        padding: 0.7rem 1rem;
        border-radius: 1rem;
        line-height: 1.6;
        word-wrap: break-word;
        box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }
    .chat-bubble.assistant {
        background-color: #F4F4F4;
        border: 1px solid #E0E0E0;
        color: #000;
        border-top-left-radius: 0.3rem;
    }
    .chat-bubble.user {
        background-color: #DCF2FF;
        border: 1px solid #CDE9FF;
        color: #000;
        border-top-right-radius: 0.3rem;
    }
    .avatar {
        width: 36px; height: 36px;
        border-radius: 50%;
        display: flex; align-items: center; justify-content: center;
        font-size: 18px; font-weight: bold;
        background-color: #E5E7EB;
        margin: 0 0.5rem;
    }
    .avatar.user { background-color: #CDE9FF; }
    input, button, label, div[data-testid="stMarkdownContainer"] {
        font-size: 15px !important;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown('<div class="chat-container">', unsafe_allow_html=True)
for msg in st.session_state["compare_history"]:
    role = msg["role"]
    text = msg["content"]

    if role == "assistant":
        evidence_dict = msg.get("evidence_dict", {})
        formatted_evidence = format_evidence_dict(evidence_dict)
        retrieved_docs = msg.get("retrieved_docs", [])
        formatted_sources = format_retrieved_docs(retrieved_docs) if retrieved_docs else ""
        compare_sections = msg.get("compare_sections", {})
        is_followup = bool(msg.get("is_followup", False))

        answer_body = text
        answer_body_is_html = False
        if (not is_followup) and compare_sections and not compare_sections.get("_parse_failed"):
            answer_body = format_compare_tables(compare_sections)
            answer_body_is_html = True

        answer_body_html = answer_body if answer_body_is_html else markdown_to_html(answer_body)

        if retrieved_docs:
            display_content = f"""
<div class="chat-row assistant">
<div class="avatar assistant">&#x1F914;</div>
<div class="chat-bubble assistant">
{answer_body_html}
{"<br><br><b>Evidence:</b><br><em style='color: #666; font-size: 0.9em;'>Direct quotes from official documents that support the answer above.</em><ul style='margin-top:0.5rem; padding-left:1.5rem;'>" + formatted_evidence + "</ul>" if evidence_dict else ""}
<strong>&#x1F4DA; Retrieved Sources:</strong><br>
<em style="color: #666; font-size: 0.9em;">Document snippets that were retrieved and analyzed to answer your question.</em>
<ul style="margin-top: 0.5rem; padding-left: 1.5rem;">
{formatted_sources}
</ul>
</div>
</div>
"""
            if (not is_followup) and compare_sections and not compare_sections.get("_parse_failed"):
                st.html(_wrap_compare_html(display_content))
            else:
                st.markdown(display_content, unsafe_allow_html=True)
        else:
            display_content = f"""
<div class="chat-row assistant">
<div class="avatar assistant">&#x1F914;</div>
<div class="chat-bubble assistant">
{answer_body_html}
{"" if not evidence_dict else f"<br><br><b>Evidence:</b><br><em style='color: #666; font-size: 0.9em;'>Direct quotes from official documents that support the answer above.</em><ul style='margin-top:0.5rem; padding-left:1.5rem;'>{formatted_evidence}</ul>"}
</div>
</div>
"""
            if (not is_followup) and compare_sections and not compare_sections.get("_parse_failed"):
                st.html(_wrap_compare_html(display_content))
            else:
                st.markdown(display_content, unsafe_allow_html=True)
    else:
        safe_text = html.escape(text)
        st.markdown(
            f"""<div class="chat-row user">
                <div class="chat-bubble user">{safe_text}</div>
                <div class="avatar user">&#x1F464;</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
st.markdown('</div>', unsafe_allow_html=True)

# ============================================================
# ========== FOLLOW-UP QUESTION BUTTONS ======================
# ============================================================
if st.session_state["compare_history"]:
    last_msg = st.session_state["compare_history"][-1]
    if last_msg.get("role") == "assistant":
        has_suggestions = bool(last_msg.get("followup_questions"))
        if has_suggestions:
            st.markdown("**Suggested follow-up questions:**")
            cols = st.columns(len(last_msg["followup_questions"]))
            for i, (col, q) in enumerate(zip(cols, last_msg["followup_questions"])):
                with col:
                    if st.button(q, key=f"compare_followup_{i}"):
                        st.session_state["compare_history"].append({"role": "user", "content": q})
                        st.session_state["compare_pending_query"] = q
                        st.session_state["compare_pending_is_followup"] = True
                        st.rerun()

        with st.form("compare_followup_form", clear_on_submit=True):
            followup_query = st.text_input(
                "**Or ask your own follow-up:**",
                placeholder="Type a follow-up question here (keeps comparison context)...",
            )
            followup_submitted = st.form_submit_button("Ask Follow-Up")
        if followup_submitted and followup_query.strip():
            st.session_state["compare_history"].append({"role": "user", "content": followup_query})
            st.session_state["compare_pending_query"] = followup_query
            st.session_state["compare_pending_is_followup"] = True
            st.rerun()

# ============================================================
# ========== INPUT AREA ======================================
# ============================================================
with st.container():
    st.markdown('<div class="input-box">', unsafe_allow_html=True)

    with st.form("compare_form", clear_on_submit=True):
        user_query = st.text_input(
            "🔎 **Compare a Concept:**",
            placeholder="e.g. Define 'medical necessity' in policy vs provider manual.",
        )

        col1, col2 = st.columns([1, 1])
        with col1:
            submitted = st.form_submit_button("🔍 Compare", use_container_width=True)
        with col2:
            cleared = st.form_submit_button("🧹 Clear", use_container_width=True)

    st.markdown('</div>', unsafe_allow_html=True)

# ============================================================
# ========== CLEAR / SUBMIT ==================================
# ============================================================
if cleared:
    st.session_state["compare_history"] = []
    rag_pipeline = st.session_state.get("compare_rag_pipeline")
    if rag_pipeline:
        try:
            rag_pipeline.chat_history.clear()
        except Exception as e:
            st.error(f"Error clearing chat history: {e}")
    st.rerun()

# Submit logic ? phase 1
if submitted:
    if not user_query.strip():
        st.warning("Please enter a concept before comparing.")
    else:
        st.session_state["compare_history"] = [{"role": "user", "content": user_query}]
        rag_pipeline = st.session_state.get("compare_rag_pipeline")
        if rag_pipeline:
            try:
                rag_pipeline.chat_history.clear()
            except Exception:
                pass
        st.session_state["compare_pending_query"] = user_query
        st.session_state["compare_pending_is_followup"] = False
        st.rerun()

# Submit logic — phase 2
if "compare_pending_query" in st.session_state:
    pending_query = st.session_state.pop("compare_pending_query")
    pending_is_followup = st.session_state.pop("compare_pending_is_followup", False)
    with st.spinner("Retrieving information..." if pending_is_followup else "Comparing definitions..."):
        try:
            rag_pipeline = get_rag_pipeline_lazy()
            if rag_pipeline:
                if pending_is_followup:
                    history_for_llm = st.session_state["compare_history"]
                    result = rag_pipeline.answer_question(pending_query, history=history_for_llm)
                    answer = result.get("answer", "No answer returned.")
                    evidence_dict = result.get("evidence_dict", {})
                    retrieved_docs = result.get("retrieved_docs", [])
                    followup_questions = result.get("followup_questions", [])
                    compare_sections = {}
                else:
                    result = rag_pipeline.answer_compare_definitions(
                        pending_query,
                        concept=pending_query,
                    )
                    answer = result.get("answer", "No answer returned.")
                    evidence_dict = result.get("evidence_dict", {})
                    retrieved_docs = result.get("retrieved_docs", [])
                    followup_questions = result.get("followup_questions", [])
                    compare_sections = result.get("compare_sections", {})
                    if isinstance(retrieved_docs, dict):
                        policy_docs = retrieved_docs.get("policy", []) or []
                        provider_docs = retrieved_docs.get("provider_manual", []) or []
                        retrieved_docs = policy_docs + provider_docs
            else:
                answer = (
                    "Mock mode: Backend not connected.\n"
                    "No grounded answer can be generated. "
                    "Please connect the backend (RAG pipeline) to enable cited answers."
                )
                evidence_dict = {}
                retrieved_docs = []
                followup_questions = []
                compare_sections = {}
            st.session_state["compare_history"].append({
                "role": "assistant",
                "content": answer,
                "evidence_dict": evidence_dict,
                "retrieved_docs": retrieved_docs,
                "compare_sections": compare_sections,
                "followup_questions": followup_questions,
                "is_followup": pending_is_followup,
            })
            st.rerun()
        except Exception as e:
            st.session_state["compare_history"].pop()
            st.error(f"Error: {e}")
